export const URDU_TO_ENGLISH: Record<string, string> = {
  'پاکستان': 'Pakistan',
  'پاکستانی': 'Pakistani',
  'دنیا': 'world',
  'کھیل': 'sports',
  'کاروبار': 'business',
  'شوبز': 'entertainment',
  'سائنس و ٹیکنالوجی': 'technology',
  'صحت': 'health',
  'تعلیم': 'education',
  'سیاست': 'politics',
  'معیشت': 'economy',
  'کرکٹ': 'cricket',
  'فٹ بال': 'football',
  'فلم': 'movie',
  'موبائل': 'mobile',
  'ایپس': 'apps',
  'وائرس': 'virus',
  'عدالت': 'court',
  'انتخابات': 'election',
  'حکومت': 'government',
  'وزیراعظم': 'prime minister',
  'صدر': 'president',
  'آئی ایم ایف': 'IMF',
  'اسٹاک مارکیٹ': 'stock market',
  'سمارٹ فون': 'smartphone',
  'کیمرہ': 'camera',
  'بینک': 'bank',
  'تعلیمی': 'educational',
  'امتحانات': 'exams',
  'ہسپتال': 'hospital',
  'اداکار': 'actor',
  'گرمی': 'summer heat',
  'موسم': 'weather',
  'درجہ حرارت': 'temperature',
  'برآمدات': 'exports',
  'توانائی': 'energy',
  'تیل': 'oil',
  'قدرتی آفت': 'natural disaster',
  'زلزلہ': 'earthquake',
  'سیلاب': 'flood',
  'بارش': 'rain',
  'اجلاس': 'summit meeting',
  'معاہدہ': 'agreement',
  'امن': 'peace',
  'جنگ بندی': 'ceasefire',
  'جنگ': 'war',
  'فوج': 'army',
  'پولیس': 'police',
  'عدالت عظمی': 'supreme court',
  'جج': 'judge',
  'ووٹ': 'vote',
  'قانون': 'law',
  'منصوبہ': 'project plan',
  'منصوبے': 'project',
  'ترقی': 'development',
  'غربت': 'poverty',
  'تعمیر': 'construction',
  'ریلوے': 'railway',
  'سڑک': 'road highway',
  'پانی': 'water',
  'بجلی': 'electricity',
  'زراعت': 'agriculture farming',
  'فصل': 'crop harvest',
  'اضافہ': 'increase',
  'کمی': 'decrease',
  'شرح': 'rate',
  'متوقع': 'expected',
  'مہنگائی': 'inflation',
  'بجٹ': 'budget',
  'وفاقی': 'federal',
  'تنخواہوں': 'salaries',
  'آمد': 'arrival',
  'گرما': 'summer',
  'سالانہ': 'annual',
  'اداروں': 'institutions',
  'آغاز': 'start',
  'سہولتوں': 'facilities',
  'بہتری': 'improvement',
  'مشہور': 'famous',
  'اعلان': 'announcement',
  'چین': 'China',
  'اقتصادی': 'economic',
  'راہداری': 'corridor',
  'تیزی': 'rapid growth',
  'شیڈول': 'schedule',
  'جاری': 'released ongoing',
  'روپے': 'rupee',
  'قدر': 'value',
  'ڈالر': 'dollar',
  'سستا': 'cheaper',
  'نمایاں': 'significant',
  'ڈرامہ': 'drama',
  'سیریل': 'serial',
  'بھارت': 'India',
  'مقبولیت': 'popularity',
  'حاصل': 'gained',
  'لوک': 'folk',
  'میوزک': 'music',
  'فیسٹیول': 'festival',
  'انعقاد': 'held',
  'فنکاروں': 'artists',
  'شرکت': 'participation',
  'سروس': 'service',
  'اجراء': 'launch',
  'تیاریاں': 'preparations',
  'ڈینگی': 'dengue',
  'بخار': 'fever',
  'بچاؤ': 'prevention',
  'احتیاطی': 'preventive',
  'تدابیر': 'measures',
  'پولیو': 'polio',
  'قطرہ': 'drop',
  'مہم': 'campaign',
  'نصاب': 'curriculum',
  'عملی': 'practical',
  'زندگی': 'life',
  'توجہ': 'focus',
  'طلبہ': 'students',
  'اسکالرشپ': 'scholarship',
  'پروگرام': 'program',
  'پی ایس ایل': 'PSL',
  'انڈیکس': 'index',
  'لیگ': 'league',
  'ٹیم': 'team',
  'کھلاڑیوں': 'players',
  'میچ': 'match',
  'ٹورنامنٹ': 'tournament',
  'سیریز': 'series',
  'شکست': 'defeat',
  'فتح': 'victory',
  'ریکارڈ': 'record',
  'لہر': 'wave',
  'سی پیک': 'CPEC',
  'قومی': 'national',
  'بورڈ': 'board',
  'سروسز': 'services',
  'نیٹ': 'internet',
  'امتحان': 'exam examination',
  'نتیجہ': 'result outcome',
  'پوزیشن': 'position rank',
  'درجہ': 'positiongrade ranking',
  'سرٹیفکیٹ': 'certificate',
  'ڈگری': 'degree',
  'ماسٹر': 'master',
  'ڈاکٹر': 'doctor',
  'انجینئرنگ': 'engineering',
  'میڈیکل': 'medical',
  'فن': 'art fine arts',
  'کاروباری': 'business entrepreneurial',
  'وظیفہ': 'job employment',
  'بیروزگاری': 'unemployment',
  'معاشی': 'economic',
  'مالی': 'financial monetary',
  'خزانہ': 'treasury finance',
  'ٹیکس': 'tax',
  'محصول': 'revenue',
  'خرچ': 'expenditure expense',
  'قرض': 'debt loan',
  'بچت': 'savings',
  'منافع': 'profit',
  'نقصان': 'loss',
  'سرمایہ': 'capital investment',
  'کارخانہ': 'factory industry',
  'پیداوار': 'production output',
  'مانگ': 'demand',
  'رسد': 'supply',
  'اجناس': 'commodities goods',
  'درآمد': 'import',
  'برآمد': 'export',
  'ادھار': 'loan borrowing',
  'شرح سود': 'interest rate',
  'مبادلہ': 'exchange',
  'زر': 'gold money',
  'سون': 'gold',
  'چاندی': 'silver',
  'پیٹرول': 'petrol gasoline',
  'ڈیزل': 'diesel',

  'یورپ': 'Europe',
  'امریکی': 'American US',
  'صدارتی': 'presidential',
  'فلسطین': 'Palestine',
  'اقوام متحدہ': 'United Nations',
  'کوششیں': 'efforts',
  'مصنوعی ذہانت': 'artificial intelligence',
  'شعبے': 'sector',
  'انقلاب': 'revolution',
  'نیا': 'new',
  'نئی': 'new',
  'نئے': 'new',
  'مارکیٹ': 'market',
  'جلد': 'soon',
  'متعارف': 'introduced',
  'تبدیلی': 'change',
  'ملک': 'country',
  'شہر': 'city',
  'وزیر': 'minister',
  'صوبائی': 'provincial',
  'مقامی': 'local',
  'عالمی': 'global',
  'فیصلہ': 'decision',
  'اہم': 'important',
  'بڑے': 'major',
  'کامیاب': 'successful',
  'شامل': 'included',
  'تازہ': 'fresh latest',
  'ترجمان': 'spokesperson',
  'ذرائع': 'sources',
  'غیر ملکی': 'foreign',
  'مقابلہ': 'competition',
  'فعال': 'active',
  'قائم': 'established',
  'واقع': 'occurred',
  'اور': 'and',
  'کے': 'of',
  'میں': 'in',
  'لیے': 'for',
  'سے': 'from',
  'کا': 'of',
  'کی': 'of',
  'کو': 'to',
  'پر': 'on',
  'طے پا گیا': 'finalized',
  'پیش': 'presented',
  'توڑ': 'broke',
  'تیز': 'intensified',
  'انقلابی': 'revolutionary',
  'تیار': 'prepared',
  'کا آغاز': 'started',
  'ہے': 'is',
  'ہیں': 'are',
  'گیا': 'was',
  'گئی': 'was',
  'گئے': 'were',
  'ہو': 'been',
  'خلاف': 'against',
  'ساتھ': 'with',
  'بعد': 'after',
  'قبل': 'before',
  'دوران': 'during',
  'بغیر': 'without',
  'صرف': 'only',
  'ہر': 'every',
  'کچھ': 'some',
  'بہت': 'very',
  'ان': 'these',
  'اس': 'this',
  'ایک': 'one',
  'اور بھی': 'more',
  'دیگر': 'other',
  'مزید': 'further',
  'نے': '',
  'بھی': 'also',
  'ہوا': 'was',
  'ہوئی': 'was',
  'ہوئے': 'were',
  'رہا': 'remained',
  'رہی': 'remained',
  'رہے': 'remained',
  'کیا': 'done',
  'کئے': 'done',
  'دی': 'given',
  'دیا': 'given',
  'دیے': 'given',
  'جا': 'being',
  'گا': 'will',
  'گی': 'will',
  'ہوگا': 'will be',
  'ہوگی': 'will be',
  'ہوں گے': 'will be',
  'سکتا': 'can',
  'سکتی': 'can',
  'سکتے': 'can',
  'چاہیے': 'should',
  'ضروری': 'necessary',
  'ممکن': 'possible',
  'کہ': 'that',
  'جن': 'who',
  'جو': 'which',
  'وہ': 'that',
  'یہ': 'this',
  'آپ': 'you',
  'ہم': 'we',
  'انہوں': 'they',
  'ان کا': 'their',
  'اپنے': 'own',
  'اپنی': 'own',
  'اپنا': 'own',
};

export function translateToEnglish(urduText: string): string {
  let result = urduText;
  const sorted = Object.entries(URDU_TO_ENGLISH).sort((a, b) => b[0].length - a[0].length);
  for (const [urdu, english] of sorted) {
    result = result.replace(new RegExp(urdu, 'g'), english);
  }
  return result;
}

const URDU_REGEX = /[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]/g;

export function translateToCleanEnglish(urduText: string): string {
  const translated = translateToEnglish(urduText);
  return translated.replace(URDU_REGEX, '').replace(/\s+/g, ' ').trim();
}

export const ENGLISH_TO_URDU: Record<string, string> = {};

function buildReverseMap() {
  for (const [urdu, english] of Object.entries(URDU_TO_ENGLISH)) {
    const words = english.toLowerCase().split(/\s+/);
    for (const word of words) {
      if (word.length > 2 && !ENGLISH_TO_URDU[word]) {
        ENGLISH_TO_URDU[word] = urdu;
      }
    }
  }
  const manual: Record<string, string> = {
    'the': '',
    'a': 'ایک',
    'an': 'ایک',
    'is': 'ہے',
    'are': 'ہیں',
    'was': 'تھا',
    'were': 'تھے',
    'be': 'ہو',
    'been': 'ہوا',
    'to': 'کو',
    'of': 'کا',
    'in': 'میں',
    'for': 'کے لیے',
    'on': 'پر',
    'by': 'کی طرف سے',
    'with': 'کے ساتھ',
    'at': 'میں',
    'from': 'سے',
    'and': 'اور',
    'or': 'یا',
    'but': 'لیکن',
    'not': 'نہیں',
    'has': 'رکھتا ہے',
    'have': 'رکھتے ہیں',
    'had': 'تھا',
    'its': 'اس کا',
    'this': 'یہ',
    'that': 'وہ',
    'these': 'یہ',
    'those': 'وہ',
    'it': 'یہ',
    'he': 'وہ',
    'she': 'وہ',
    'they': 'وہ',
    'we': 'ہم',
    'you': 'آپ',
    'will': 'گا',
    'would': 'گا',
    'can': 'سکتا ہے',
    'could': 'سکتا تھا',
    'should': 'چاہیے',
    'may': 'سکتا ہے',
    'might': 'سکتا تھا',
    'do': 'کرتا ہے',
    'does': 'کرتا ہے',
    'did': 'کیا',
    'after': 'کے بعد',
    'before': 'سے پہلے',
    'during': 'کے دوران',
    'over': 'سے زیادہ',
    'under': 'کے نیچے',
    'between': 'کے درمیان',
    'about': 'کے بارے میں',
    'into': 'میں',
    'through': 'کے ذریعے',
    'against': 'کے خلاف',
    'new': 'نیا',
    'old': 'پرانا',
    'more': 'مزید',
    'less': 'کم',
    'many': 'بہت سے',
    'much': 'بہت',
    'some': 'کچھ',
    'any': 'کوئی',
    'all': 'تمام',
    'each': 'ہر',
    'every': 'ہر',
    'other': 'دوسرے',
    'such': 'ایسا',
    'no': 'نہیں',
    'own': 'اپنا',
    'very': 'بہت',
    'just': 'صرف',
    'also': 'بھی',
    'only': 'صرف',
    'now': 'اب',
    'then': 'پھر',
    'here': 'یہاں',
    'there': 'وہاں',
    'when': 'جب',
    'where': 'جہاں',
    'why': 'کیوں',
    'how': 'کیسے',
    'what': 'کیا',
    'which': 'جو',
    'who': 'جو',
    'whom': 'جسے',
    'whose': 'جس کا',
    'if': 'اگر',
    'than': 'سے',
    'so': 'تو',
    'as': 'جبکہ',
    'while': 'جبکہ',
    'though': 'اگرچہ',
    'because': 'کیونکہ',
    'up': 'اوپر',
    'down': 'نیچے',
    'out': 'باہر',
    'off': 'بند',
    'away': 'دور',
    'back': 'واپس',
    'still': 'اب بھی',
    'yet': 'ابھی تک',
    'already': 'پہلے ہی',
    'ever': 'کبھی',
    'never': 'کبھی نہیں',
    'always': 'ہمیشہ',
    'often': 'اکثر',
    'sometimes': 'کبھی کبھی',
    'usually': 'عام طور پر',
    'once': 'ایک بار',
    'again': 'پھر',
    'well': 'اچھی طرح',
    'even': 'یہاں تک کہ',
    'really': 'واقعی',
    'quite': 'کافی',
    'enough': 'کافی',
    'rather': 'بلکہ',
    'around': 'ارد گرد',
    'along': 'کے ساتھ ساتھ',
    'among': 'کے درمیان',
    'beyond': 'سے باہر',
    'without': 'بغیر',
    'within': 'کے اندر',
    'across': 'بھر',
    'despite': 'کے باوجود',
    'since': 'سے',
    'until': 'تک',
    'upon': 'پر',
    'via': 'کے ذریعے',
    'per': 'فی',
    'toward': 'کی طرف',
    'like': 'جیسے',
    'unlike': 'کے برعکس',
    'top': 'سب سے اوپر',
    'behind': 'پیچھے',
    'ahead': 'آگے',
    'next': 'اگلا',
    'last': 'آخری',
    'first': 'پہلا',
    'second': 'دوسرا',
    'third': 'تیسرا',
    'latest': 'تازہ ترین',
    'breaking': 'بریکنگ',
    'live': 'لائیو',
    'update': 'اپ ڈیٹ',
    'report': 'رپورٹ',
    'watch': 'دیکھیں',
    'video': 'ویڈیو',
    'photo': 'تصویر',
    'picture': 'تصویر',
    'image': 'تصویر',
    'world': 'دنیا',
    'global': 'عالمی',
    'international': 'بین الاقوامی',
    'local': 'مقامی',
    'national': 'قومی',
    'regional': 'علاقائی',
    'city': 'شہر',
    'country': 'ملک',
    'people': 'لوگ',
    'official': 'سرکاری',
    'president': 'صدر',
    'minister': 'وزیر',
    'government': 'حکومت',
    'police': 'پولیس',
    'court': 'عدالت',
    'judge': 'جج',
    'law': 'قانون',
    'election': 'انتخابات',
    'vote': 'ووٹ',
    'political': 'سیاسی',
    'party': 'جماعت',
    'leader': 'رہنما',
    'attack': 'حملہ',
    'killed': 'ہلاک',
    'dead': 'مرنے والے',
    'injured': 'زخمی',
    'death': 'موت',
    'hospital': 'ہسپتال',
    'doctor': 'ڈاکٹر',
    'health': 'صحت',
    'disease': 'بیماری',
    'treatment': 'علاج',
    'drug': 'دوا',
    'vaccine': 'ویکسین',
    'covid': 'کوویڈ',
    'coronavirus': 'کورونا وائرس',
    'pandemic': 'وبا',
    'climate': 'آب و ہوا',
    'weather': 'موسم',
    'temperature': 'درجہ حرارت',
    'earthquake': 'زلزلہ',
    'flood': 'سیلاب',
    'rain': 'بارش',
    'storm': 'طوفان',
    'disaster': 'آفت',
    'crisis': 'بحران',
    'war': 'جنگ',
    'peace': 'امن',
    'russian': 'روسی',
    'american': 'امریکی',
    'britain': 'برطانیہ',
    'british': 'برطانوی',
    'france': 'فرانس',
    'french': 'فرانسیسی',
    'germany': 'جرمنی',
    'german': 'جرمن',
    'japanese': 'جاپانی',
    'ukraine': 'یوکرین',
    'ukrainian': 'یوکرینی',
    'australia': 'آسٹریلیا',
    'australian': 'آسٹریلوی',
    'canada': 'کینیڈا',
    'canadian': 'کینیڈین',
    'washington': 'واشنگٹن',
    'london': 'لندن',
    'paris': 'پیرس',
    'moscow': 'ماسکو',
    'beijing': 'بیجنگ',
    'kabul': 'کابل',
    'tehran': 'تہران',
    'baghdad': 'بغداد',
    'cairo': 'قاہرہ',
    'islamabad': 'اسلام آباد',
    'karachi': 'کراچی',
    'lahore': 'لاہور',
    'gaza': 'غزہ',
    'jerusalem': 'یروشلم',
    'dubai': 'دبئی',
    'nato': 'نیٹو',
    'hamas': 'حماس',
    'hezbollah': 'حزب اللہ',
    'taliban': 'طالبان',
    'pentagon': 'پینٹاگن',
    'trump': 'ٹرمپ',
    'biden': 'بائیڈن',
    'putin': 'پیوٹن',
    'zelensky': 'زیلنسکی',
    'netanyahu': 'نیتن یاہو',
    'modi': 'مودی',
    'khan': 'خان',
    'st petersburg': 'سینٹ پیٹرزبرگ',
    'cafe': 'کیفے',
    'suspects': 'ملزمان',
    'bombings': 'بم دھماکے',
    'authorities': 'حکام',
    'says': 'کہتے ہیں',
    'sources': 'ذرائع',
    'source': 'ماخذ',
    'according': 'مطابق',
    'struck': 'حملہ کیا',
    'iranian': 'ایرانی',
    'radar': 'ریڈار',
    'sites': 'مقامات',
    'kuwait': 'کویت',
    'reports': 'رپورٹیں',
    'missiles': 'میزائل',
    'drones': 'ڈرون',
    'rugby': 'رگبی',
    'legend': 'افسانہ',
    'broadcaster': 'بروڈکاسٹر',
    'dies': 'انتقال کر گئے',
    'aged': 'عمر',
    'later': 'بعد میں',
    'soon': 'جلد',
    'earlier': 'پہلے',
    'currently': 'فی الحال',
    'ongoing': 'جاری',
    'updated': 'اپ ڈیٹ شدہ',
    'exclusive': 'خصوصی',
    'editorial': 'اداریہ',
    'feature': 'فیچر',
    'coverage': 'کوریج',
    'developing': 'تیار ہونے والی',
    'reportedly': 'بتایا جاتا ہے',
    'unconfirmed': 'غیر مصدقہ',
    'several': 'کئی',
    'multiple': 'متعدد',
    'massive': 'بڑے پیمانے پر',
    'entire': 'پورا',
    'total': 'کل',
    'floods': 'سیلاب',
    'million': 'ملین',
    'billion': 'ارب',
    'thousand': 'ہزار',
    'percent': 'فیصد',
    'patients': 'مریض',
    'recover': 'صحت یابی',
    'recovered': 'صحت یاب',
    'defeated': 'شکست دی',
    'won': 'جیت لیا',
    'lost': 'ہار گیا',
    'champion': 'چیمپئن',
    'champions': 'چیمپئن',
    'markets': 'مارکیٹیں',
    'stocks': 'اسٹاک',
    'profits': 'منافع',
    'losses': 'نقصانات',
    'loans': 'قرضے',
    'taxes': 'ٹیکس',
    'tariffs': 'ٹیرف',
    'exports': 'برآمدات',
    'imports': 'درآمدات',
    'investments': 'سرمایہ کاری',
    'investors': 'سرمایہ کار',
    'companies': 'کمپنیاں',
    'banks': 'بینک',
    'banking': 'بینکنگ',
    'unemployment': 'بے روزگاری',
    'employment': 'روزگار',
    'schools': 'سکول',
    'students': 'طلباء',
    'teachers': 'اساتذہ',
    'artificial': 'مصنوعی',
    'crime': 'جرم',
    'crimes': 'جرائم',
    'criminal': 'مجرم',
    'terror': 'دہشت',
    'protests': 'احتجاجات',
    'elections': 'انتخابات',
    'voting': 'رائے شماری',
    'governor': 'گاورنر',
    'presidential': 'صدراتی',
    'prime minister': 'وزیراعظم',
    'parliamentary': 'پارلیمینٹری',
    'leaders': 'رہنماء',
    'speaker': 'سپیکر',
    'soldiers': 'فوجی',
    'ceasefire': 'جنگ بندی',
    'military': 'فوجی',
    'army': 'فوج',
    'soldier': 'فوجی',
    'india': 'بھارت',
    'pakistan': 'پاکستان',
    'america': 'امریکہ',
    'us': 'امریکہ',
    'uk': 'برطانیہ',
    'europe': 'یورپ',
    'russia': 'روس',
    'iran': 'ایران',
    'afghanistan': 'افغانستان',
    'palestine': 'فلسطین',
    'israel': 'اسرائیل',
    'turkey': 'ترکی',
    'saudi': 'سعودی',
    'china': 'چین',
    'japan': 'جاپان',
    'kashmir': 'کشمیر',
    'sports': 'کھیل',
    'football': 'فٹ بال',
    'cricket': 'کرکٹ',
    'tennis': 'ٹینس',
    'hockey': 'ہاکی',
    'olympic': 'اولمپک',
    'match': 'میچ',
    'game': 'کھیل',
    'player': 'کھلاڑی',
    'team': 'ٹیم',
    'coach': 'کوچ',
    'tournament': 'ٹورنامنٹ',
    'championship': 'چیمپئن شپ',
    'league': 'لیگ',
    'final': 'فائنل',
    'win': 'جیت',
    'loss': 'ہار',
    'score': 'سکور',
    'goal': 'گول',
    'business': 'کاروبار',
    'economy': 'معیشت',
    'market': 'مارکیٹ',
    'stock': 'اسٹاک',
    'bank': 'بینک',
    'money': 'پیسہ',
    'dollar': 'ڈالر',
    'rupee': 'روپے',
    'price': 'قیمت',
    'rate': 'شرح',
    'trade': 'تجارت',
    'export': 'برآمد',
    'import': 'درآمد',
    'tax': 'ٹیکس',
    'budget': 'بجٹ',
    'debt': 'قرض',
    'loan': 'قرض',
    'inflation': 'مہنگائی',
    'profit': 'منافع',
    'company': 'کمپنی',
    'industry': 'صنعت',
    'technology': 'ٹیکنالوجی',
    'tech': 'ٹیک',
    'digital': 'ڈیجیٹل',
    'internet': 'انٹرنیٹ',
    'phone': 'فون',
    'mobile': 'موبائل',
    'computer': 'کمپیوٹر',
    'software': 'سافٹ ویئر',
    'app': 'ایپ',
    'data': 'ڈیٹا',
    'ai': 'AI',
    'robot': 'روبوٹ',
    'space': 'خلاء',
    'science': 'سائنس',
    'research': 'تحقیق',
    'education': 'تعلیم',
    'school': 'سکول',
    'university': 'یونیورسٹی',
    'college': 'کالج',
    'student': 'طالب علم',
    'teacher': 'استاد',
    'exam': 'امتحان',
    'result': 'نتیجہ',
    'entertainment': 'تفریح',
    'movie': 'فلم',
    'film': 'فلم',
    'music': 'موسیقی',
    'song': 'گیت',
    'actor': 'اداکار',
    'actress': 'اداکارہ',
    'singer': 'گلوکار',
    'drama': 'ڈرامہ',
    'show': 'شو',
    'festival': 'تہوار',
    'award': 'ایوارڈ',
    'celebrity': 'مشہور شخصیت',
    'famous': 'مشہور',
    'culture': 'ثقافت',
    'art': 'فن',
    'book': 'کتاب',
    'writer': 'مصنف',
    'author': 'مصنف',
    'news': 'خبر',
    'media': 'میڈیا',
    'press': 'پریس',
    'journalist': 'صحافی',
    'editor': 'ایڈیٹر',
    'publish': 'شائع',
    'article': 'مضمون',
    'headline': 'سرخی',
    'story': 'کہانی',
    'hour': 'گھنٹہ',
    'day': 'دن',
    'week': 'ہفتہ',
    'month': 'مہینہ',
    'year': 'سال',
    'today': 'آج',
    'yesterday': 'کل',
    'tomorrow': 'کل',
    'morning': 'صبح',
    'evening': 'شام',
    'night': 'رات',
    'time': 'وقت',
    'date': 'تاریخ',
    'minute': 'منٹ',
    'ago': 'پہلے',
    'early': 'ابتدائی',
    'late': 'دیر',
    'recent': 'حالیہ',
    'current': 'موجودہ',
    'previous': 'گزشتہ',
    'coming': 'آنے والا',
    'upcoming': 'آنے والا',
    'future': 'مستقبل',
    'past': 'ماضی',
    'young': 'جوان',
    'modern': 'جدید',
    'traditional': 'روایتی',
    'major': 'اہم',
    'minor': 'معمولی',
    'key': 'اہم',
    'chief': 'سربراہ',
    'main': 'اہم',
    'primary': 'بنیادی',
    'senior': 'سینئر',
    'junior': 'جونیئر',
    'lead': 'قیادت',
    'important': 'اہم',
    'significant': 'اہم',
    'crucial': 'اہم',
    'critical': 'نازک',
    'vital': 'ضروری',
    'essential': 'ضروری',
    'necessary': 'ضروری',
    'possible': 'ممکن',
    'potential': 'ممکنہ',
    'likely': 'ممکنہ',
    'special': 'خصوصی',
    'general': 'جنرل',
    'specific': 'مخصوص',
    'particular': 'خاص',
    'individual': 'انفرادی',
    'public': 'عوام',
    'private': 'نجی',
    'domestic': 'ملکی',
    'foreign': 'غیر ملکی',
    'external': 'بیرونی',
    'internal': 'داخلی',
    'central': 'مرکزی',
    'federal': 'وفاقی',
    'provincial': 'صوبائی',
    'state': 'ریاست',
    'province': 'صوبہ',
    'district': 'ضلع',
    'capital': 'دارالحکومت',
    'parliament': 'پارلیمنٹ',
    'senate': 'سینیٹ',
    'assembly': 'اسمبلی',
    'congress': 'کانگریس',
    'opposition': 'اپوزیشن',
    'alliance': 'اتحاد',
    'coalition': 'اتحاد',
    'member': 'رکن',
    'chairman': 'چیئرمین',
    'secretary': 'سیکرٹری',
    'spokesman': 'ترجمان',
    'spokesperson': 'ترجمان',
    'authority': 'اختیار',
    'department': 'محکمہ',
    'ministry': 'وزارت',
    'agency': 'ایجنسی',
    'commission': 'کمیشن',
    'committee': 'کمیٹی',
    'council': 'کونسل',
    'board': 'بورڈ',
    'bureau': 'بیورو',
    'session': 'اجلاس',
    'summit': 'سربراہی اجلاس',
    'conference': 'کانفرنس',
    'dialogue': 'مذاکرات',
    'negotiation': 'مذاکرات',
    'talks': 'مذاکرات',
    'deal': 'معاہدہ',
    'agreement': 'معاہدہ',
    'treaty': 'معاہدہ',
    'pact': 'معاہدہ',
    'accord': 'معاہدہ',
    'bill': 'بل',
    'act': 'ایکٹ',
    'ordinance': 'آرڈیننس',
    'resolution': 'قرارداد',
    'amendment': 'ترمیم',
    'constitution': 'آئین',
    'constitutional': 'آئینی',
    'supreme': 'سپریم',
    'justice': 'انصاف',
    'chief justice': 'چیف جسٹس',
    'hearing': 'سماعت',
    'verdict': 'فیصلہ',
    'sentence': 'سزا',
    'appeal': 'اپیل',
    'petition': 'درخواست',
    'plea': 'درخواست',
    'charge': 'الزام',
    'accusation': 'الزام',
    'allegation': 'الزام',
    'evidence': 'ثبوت',
    'witness': 'گواہ',
    'trial': 'مقدمہ',
    'prosecution': 'استغاثہ',
    'defense': 'دفاع',
    'defendant': 'ملزم',
    'suspect': 'ملزم',
    'accused': 'ملزم',
    'arrest': 'گرفتاری',
    'detain': 'حراست',
    'bail': 'ضمانت',
    'prison': 'جیل',
    'jail': 'جیل',
    'release': 'رہائی',
    'convict': 'مجرم',
    'guilty': 'مجرم',
    'innocent': 'بے قصور',
    'investigation': 'تحقیقات',
    'inquiry': 'انکوائری',
    'probe': 'تحقیقات',
    'investigate': 'تحقیقات کرنا',
    'protest': 'احتجاج',
    'rally': 'ریلی',
    'march': 'مارچ',
    'demonstration': 'مظاہرہ',
    'protesters': 'مظاہرین',
    'strike': 'ہڑتال',
    'boycott': 'بائیکاٹ',
    'campaign': 'مہم',
    'policy': 'پالیسی',
    'reform': 'اصلاحات',
    'development': 'ترقی',
    'progress': 'ترقی',
    'growth': 'ترقی',
    'plan': 'منصوبہ',
    'project': 'منصوبہ',
    'program': 'پروگرام',
    'scheme': 'اسکیم',
    'initiative': 'اقدام',
    'strategy': 'حکمت عملی',
    'system': 'نظام',
    'process': 'عمل',
    'operation': 'آپریشن',
    'mission': 'مشن',
    'candidate': 'امیدوار',
    'ballot': 'بیلٹ',
    'poll': 'رائے شماری',
    'seat': 'نشست',
    'constituency': 'حلقہ',
    'term': 'مدت',
    'tenure': 'مدت',
    'resign': 'استعفیٰ',
    'resignation': 'استعفیٰ',
    'dismiss': 'برطرف',
    'suspend': 'معطل',
    'removal': 'برطرفی',
    'appoint': 'تقرری',
    'appointment': 'تقرری',
    'nominate': 'نامزد',
    'nomination': 'نامزدگی',
    'elect': 'منتخب',
    'elected': 'منتخب',
    'corruption': 'بدعنوانی',
    'scandal': 'اسکینڈل',
    'fraud': 'دھوکہ دہی',
    'bribery': 'رشوت',
    'nepotism': 'سفارش',
    'accountability': 'احتساب',
    'transparency': 'شفافیت',
    'address': 'خطاب',
    'speech': 'تقریر',
    'statement': 'بیان',
    'announcement': 'اعلان',
    'declaration': 'اعلان',
    'press conference': 'پریس کانفرنس',
    'briefing': 'بریفنگ',
    'interview': 'انٹرویو',
    'debate': 'بحث',
    'discussion': 'بات چیت',
    'consultation': 'مشاورت',
    'interaction': 'بات چیت',
    'communication': 'مواصلات',
    'message': 'پیغام',
    'response': 'جواب',
    'reply': 'جواب',
    'reaction': 'ردعمل',
    'suggestion': 'تجاویز',
    'recommendation': 'سفارش',
    'proposal': 'تجویز',
    'demand': 'مطالبہ',
    'request': 'درخواست',
    'call': 'مطالبہ',
    'urge': 'زور دینا',
    'urged': 'زور دیا',
    'ask': 'پوچھنا',
    'asked': 'پوچھا',
    'tell': 'بتانا',
    'told': 'بتایا',
    'say': 'کہنا',
    'said': 'کہا',
    'add': 'شامل کرنا',
    'confirm': 'تصدیق',
    'confirmed': 'تصدیق شدہ',
    'reveal': 'انکشاف',
    'revealed': 'انکشاف ہوا',
    'announce': 'اعلان',
    'declare': 'اعلان',
    'declared': 'اعلان کیا',
    'stated': 'بیان کیا',
    'reported': 'رپورٹ کیا',
    'claim': 'دعویٰ',
    'claimed': 'دعویٰ کیا',
    'allege': 'الزام لگانا',
    'alleged': 'الزامی',
    'accuse': 'الزام لگانا',
    'blame': 'الزام',
    'blamed': 'الزام لگایا',
    'praise': 'تعریف',
    'praised': 'تعریف کی',
    'criticize': 'تنقید',
    'criticized': 'تنقید کی',
    'criticism': 'تنقید',
    'condemn': 'مذمت',
    'condemned': 'مذمت کی',
    'denounce': 'مذمت',
    'denounced': 'مذمت کی',
    'reject': 'مسترد',
    'rejected': 'مسترد کیا',
    'accept': 'قبول',
    'accepted': 'قبول کیا',
    'approve': 'منظور',
    'approved': 'منظور شدہ',
    'approval': 'منظوری',
    'deny': 'انکار',
    'denied': 'انکار کیا',
    'refuse': 'انکار',
    'refused': 'انکار کیا',
    'agree': 'اتفاق',
    'agreed': 'اتفاق کیا',
    'sign': 'دستخط',
    'signed': 'دستخط شدہ',
    'signing': 'دستخط',
    'launch': 'شروع',
    'launched': 'شروع کیا',
    'start': 'شروع',
    'started': 'شروع ہوا',
    'begin': 'شروع',
    'began': 'شروع ہوا',
    'end': 'ختم',
    'ended': 'ختم ہوا',
    'stop': 'روکنا',
    'stopped': 'روک دیا',
    'continue': 'جاری',
    'continued': 'جاری رہا',
    'remain': 'رہنا',
    'remained': 'رہا',
    'keep': 'رکھنا',
    'kept': 'رکھا',
    'set': 'مقرر',
    'make': 'بنانا',
    'made': 'بنایا',
    'take': 'لینا',
    'took': 'لیا',
    'give': 'دینا',
    'gave': 'دیا',
    'put': 'رکھنا',
    'hold': 'منعقد',
    'held': 'منعقد کیا',
    'propose': 'تجویز',
    'proposed': 'تجویز کردہ',
    'suggest': 'مشورہ',
    'suggested': 'مشورہ دیا',
    'warn': 'انتباہ',
    'warned': 'انتباہ کیا',
    'warning': 'انتباہ',
    'threat': 'دھمکی',
    'threaten': 'دھمکی دینا',
    'threatened': 'دھمکی دی',
    'force': 'طاقت',
    'navy': 'بحریہ',
    'air force': 'فضائیہ',
    'marine': 'میرین',
    'troops': 'فوجی',
    'security': 'سیکورٹی',
    'intelligence': 'انٹیلی جنس',
    'surveillance': 'نگرانی',
    'attacked': 'حملہ کیا',
    'raid': 'چھاپہ',
    'assault': 'حملہ',
    'ambush': 'گھات لگانا',
    'blast': 'دھماکہ',
    'explosion': 'دھماکہ',
    'explode': 'دھماکہ',
    'bomb': 'بم',
    'bombing': 'بم دھماکہ',
    'missile': 'میزائل',
    'drone': 'ڈرون',
    'rocket': 'راکٹ',
    'shelling': 'گولہ باری',
    'firing': 'فائرنگ',
    'gunfire': 'گولی باری',
    'shooting': 'فائرنگ',
    'gunshot': 'گولی',
    'bullet': 'گولی',
    'weapon': 'ہتھیار',
    'arms': 'اسلحہ',
    'nuclear': 'جوہری',
    'atomic': 'ایٹمی',
    'suicide': 'خودکش',
    'suicide bomb': 'خودکش بم',
    'target': 'ہدف',
    'targeted': 'ہدف بنایا',
    'destroy': 'تباہ',
    'destroyed': 'تباہ ہوگیا',
    'damage': 'نقصان',
    'damaged': 'نقصان پہنچا',
    'casualty': 'ہلاکت',
    'casualties': 'ہلاکتیں',
    'deaths': 'اموات',
    'died': 'مر گیا',
    'kill': 'مارنا',
    'murder': 'قتل',
    'murdered': 'قتل کیا',
    'injure': 'زخمی',
    'wound': 'زخم',
    'wounded': 'زخمی',
    'victim': 'متاثرہ',
    'victims': 'متاثرین',
    'survivor': 'زندہ بچنے والا',
    'rescue': 'ریسکیو',
    'rescued': 'بچایا گیا',
    'relief': 'امدادی',
    'aid': 'امداد',
    'assistance': 'مدد',
    'support': 'حمایت',
    'help': 'مدد',
    'donation': 'عطیہ',
    'fund': 'فنڈ',
    'funding': 'فنڈنگ',
    'grant': 'گرانٹ',
    'package': 'پیکیج',
    'emergency': 'ایمرجنسی',
    'conflict': 'تنازعہ',
    'dispute': 'تنازعہ',
    'tension': 'کشیدگی',
    'violence': 'تشدد',
    'bloodshed': 'خون ریزی',
    'massacre': 'قتل عام',
    'atrocity': 'ظلم',
    'genocide': 'نسل کشی',
    'humanitarian': 'انسانی ہمدردی',
    'refugee': 'پناہ گزین',
    'migrant': 'مہاجر',
    'displaced': 'بے گھر',
    'border': 'سرحد',
    'boundary': 'حدود',
    'territory': 'علاقہ',
    'region': 'علاقہ',
    'sector': 'سیکٹر',
    'zone': 'زون',
    'area': 'علاقہ',
    'economic': 'اقتصادی',
    'financial': 'مالی',
    'fiscal': 'مالی',
    'monetary': 'مالیاتی',
    'deficit': 'خسارہ',
    'surplus': 'سرپلس',
    'revenue': 'آمدنی',
    'income': 'آمدنی',
    'salary': 'تنخواہ',
    'wage': 'اجرت',
    'pension': 'پنشن',
    'benefit': 'فائدہ',
    'taxation': 'ٹیکسیشن',
    'tariff': 'ٹیرف',
    'custom': 'کسٹم',
    'duty': 'ڈیوٹی',
    'investment': 'سرمایہ کاری',
    'investor': 'سرمایہ کار',
    'interest': 'سود',
    'cost': 'لاگت',
    'value': 'قدر',
    'exchange': 'ایکسچینج',
    'currency': 'کرنسی',
    'euro': 'یورو',
    'pound': 'پاؤنڈ',
    'gold': 'سونا',
    'silver': 'چاندی',
    'oil': 'تیل',
    'petroleum': 'پیٹرولیم',
    'gas': 'گیس',
    'petrol': 'پیٹرول',
    'diesel': 'ڈیزل',
    'energy': 'توانائی',
    'power': 'بجلی',
    'electricity': 'بجلی',
    'shortage': 'قلت',
    'supply': 'فراہمی',
    'consumption': 'کھپت',
    'production': 'پیداوار',
    'manufacturing': 'مینوفیکچرنگ',
    'factory': 'کارخانہ',
    'plant': 'پلانٹ',
    'infrastructure': 'انفراسٹرکچر',
    'construction': 'تعمیرات',
    'road': 'سڑک',
    'bridge': 'پل',
    'highway': 'ہائی وے',
    'motorway': 'موٹر وے',
    'railway': 'ریلوے',
    'airport': 'ہوائی اڈہ',
    'port': 'بندرگاہ',
    'tunnel': 'سرنگ',
    'dam': 'ڈیم',
    'canal': 'نہر',
    'river': 'دریا',
    'water': 'پانی',
    'agriculture': 'زراعت',
    'farming': 'کاشتکاری',
    'crop': 'فصل',
    'food': 'غذا',
    'wheat': 'گندم',
    'rice': 'چاول',
    'cotton': 'کپاس',
    'sugar': 'چینی',
    'fertilizer': 'کھاد',
    'medical': 'طبی',
    'clinic': 'کلینک',
    'nurse': 'نرس',
    'patient': 'مریض',
    'illness': 'بیماری',
    'infection': 'انفیکشن',
    'virus': 'وائرس',
    'bacteria': 'بیکٹیریا',
    'symptom': 'علامت',
    'test': 'ٹیسٹ',
    'diagnosis': 'تشخیص',
    'therapy': 'تھراپی',
    'medicine': 'دوا',
    'vaccination': 'ویکسینیشن',
    'dose': 'خوراک',
    'surgery': 'سرجری',
    'transplant': 'ٹرانسپلانٹ',
    'organ': 'عضو',
    'blood': 'خون',
    'cancer': 'کینسر',
    'diabetes': 'ذیابیطس',
    'heart': 'دل',
    'brain': 'دماغ',
    'lungs': 'پھیپھڑے',
    'kidney': 'گردہ',
    'liver': 'جگر',
    'pregnancy': 'حمل',
    'birth': 'پیدائش',
    'mortality': 'اموات',
    'epidemic': 'وبا',
    'outbreak': 'پھیلنا',
    'quarantine': 'قرنطینہ',
    'lockdown': 'لاک ڈاؤن',
    'safety': 'حفاظت',
    'educational': 'تعلیمی',
    'institute': 'انسٹی ٹیوٹ',
    'academy': 'اکیڈمی',
    'professor': 'پروفیسر',
    'lecturer': 'لیکچرر',
    'lecture': 'لیکچر',
    'class': 'کلاس',
    'classroom': 'کلاس روم',
    'course': 'کورس',
    'degree': 'ڈگری',
    'diploma': 'ڈپلومہ',
    'scholarship': 'اسکالرشپ',
    'admission': 'داخلہ',
    'enrollment': 'اندراج',
    'examination': 'امتحان',
    'grade': 'گریڈ',
    'marks': 'نمبر',
    'curriculum': 'نصاب',
    'syllabus': 'نصاب',
    'online': 'آن لائن',
    'cyber': 'سائبر',
    'hardware': 'ہارڈ ویئر',
    'smartphone': 'اسمارٹ فون',
    'network': 'نیٹ ورک',
    'satellite': 'سیٹلائٹ',
    'sport': 'کھیل',
    'captain': 'کپتان',
    'cup': 'کپ',
    'trophy': 'ٹرافی',
    'medal': 'تمغہ',
    'bronze': 'کانسی',
    'victory': 'فتح',
    'defeat': 'شکست',
    'draw': 'برابری',
    'run': 'رن',
    'wicket': 'وکٹ',
    'ball': 'گیند',
    'bat': 'بیٹ',
    'bowl': 'گیند بازی',
    'stadium': 'اسٹیڈیم',
    'ground': 'میدان',
    'field': 'میدان',
    'practice': 'مشق',
    'training': 'تربیت',
    'world cup': 'ورلڈ کپ',
    'semi final': 'سیمی فائنل',
    'quarter final': 'کوارٹر فائنل',
    'rainfall': 'بارش',
    'flooding': 'سیلاب',
    'drought': 'خشک سالی',
    'hurricane': 'سمندری طوفان',
    'tornado': 'طوفان',
    'cyclone': 'طوفان',
    'typhoon': 'طوفان',
    'tremor': 'زلزلہ',
    'snow': 'برف',
    'snowfall': 'برف باری',
    'heat': 'گرمی',
    'heatwave': 'گرمی کی لہر',
    'cold': 'سردی',
    'cold wave': 'سردی کی لہر',
    'wind': 'ہوا',
    'air': 'ہوا',
    'environment': 'ماحول',
    'pollution': 'آلودگی',
    'smog': 'سموگ',
    'carbon': 'کاربن',
    'emission': 'اخراج',
    'forest': 'جنگل',
    'wildlife': 'جنگلی حیات',
    'animal': 'جانور',
    'bird': 'پرندہ',
    'species': 'نوعیت',
    'natural': 'قدرتی',
    'conservation': 'تحفظ',
    'showbiz': 'شوبز',
    'cinema': 'سنیمہ',
    'serial': 'سیریل',
    'director': 'ہدایتکار',
    'producer': 'پروڈیوسر',
    'poet': 'شاعر',
    'artist': 'فنکار',
    'painter': 'مصور',
    'celebration': 'جشن',
    'ceremony': 'تقریب',
    'event': 'تقریب',
    'function': 'تقریب',
    'performance': 'پرفارمنس',
    'stage': 'اسٹیج',
    'concert': 'کنسرٹ',
    'prize': 'انعام',
    'heritage': 'ورثہ',
    'tradition': 'روایت',
    'fashion': 'فیشن',
    'design': 'ڈیزائن',
    'beauty': 'خوبصورتی',
    'issue': 'مسئلہ',
    'problem': 'مسئلہ',
    'matter': 'معاملہ',
    'concern': 'تشویش',
    'challenge': 'چیلنج',
    'risk': 'خطرہ',
    'danger': 'خطرہ',
    'opportunity': 'موقع',
    'chance': 'موقع',
    'situation': 'صورتحال',
    'condition': 'حالت',
    'circumstances': 'حالات',
    'background': 'پس منظر',
    'context': 'سیاق و سباق',
    'perspective': 'نقطہ نظر',
    'view': 'نقطہ نظر',
    'opinion': 'رائے',
    'analysis': 'تجزیہ',
    'analyst': 'تجزیہ کار',
    'expert': 'ماہر',
    'specialist': 'ماہر',
    'adviser': 'مشیر',
    'advisor': 'مشیر',
    'consultant': 'مشیر',
    'negotiator': 'مذاکرات کار',
    'mediator': 'ثالث',
    'representative': 'نمائندہ',
    'delegate': 'منتخب نمائندہ',
    'envoy': 'ایلچی',
    'ambassador': 'سفیر',
    'diplomat': 'سفارت کار',
    'diplomatic': 'سفارتی',
    'embassy': 'سفارت خانہ',
    'consulate': 'قونصل خانہ',
    'delegation': 'وفد',
    'sanctions': 'پابندیاں',
    'sanction': 'پابندی',
    'embargo': 'پابندی',
    'blockade': 'ناکہ بندی',
    'siege': 'محاصرہ',
    'occupation': 'قبضہ',
    'annexation': 'الحاق',
    'independence': 'آزادی',
    'sovereignty': 'خودمختاری',
    'autonomy': 'خودمختاری',
    'freedom': 'آزادی',
    'liberty': 'آزادی',
    'democracy': 'جمہوریت',
    'democratic': 'جمہوری',
    'republic': 'جمہوریہ',
    'federation': 'وفاق',
    'union': 'اتحاد',
    'community': 'برادری',
    'society': 'معاشرہ',
    'population': 'آبادی',
    'citizen': 'شہری',
    'citizens': 'شہریوں',
    'resident': 'رہائشی',
    'family': 'خاندان',
    'families': 'خاندانوں',
    'children': 'بچے',
    'women': 'خواتین',
    'men': 'مرد',
    'youth': 'نوجوان',
    'elderly': 'بزرگ',
    'minority': 'اقلیت',
    'majority': 'اکثریت',
    'rights': 'حقوق',
    'human rights': 'انسانی حقوق',
    'equality': 'مساوات',
    'plead': 'دعوی کرنا',
    'pleads': 'دعوی کرتا ہے',
    'pleaded': 'دعوی کیا',
    'felony': 'سنگین جرم',
    'count': 'شمار',
    'counts': 'شمار',
    'indictment': 'فرد جرم',
    'indict': 'فرد جرم عائد',
    'indicted': 'فرد جرم عائد',
    'charged': 'الزام عائد',
    'charges': 'الزامات',
    'allegedly': 'الزاماً',
    'convicted': 'مجرم قرار',
    'conviction': 'سزا',
    'sentenced': 'سزا سنائی',
    'sentencing': 'سزا کا اعلان',
    'arrested': 'گرفتار',
    'detained': 'حراست میں',
    'detention': 'حراست',
    'released': 'رہا',
    'bailed': 'ضمانت پر رہا',
    'prosecute': 'استغاثہ',
    'prosecuted': 'استغاثہ دائر',
    'defend': 'دفاع',
    'defended': 'دفاع کیا',
    'appealed': 'اپیل کی',
    'dismissed': 'مسترد کیا',
    'dismissal': 'برطرفی',
    'acquit': 'بری',
    'acquitted': 'بری کیا',
    'acquittal': 'بریت',
    'testify': 'گواہی دینا',
    'testified': 'گواہی دی',
    'testimony': 'گواہی',
    'witnessed': 'گواہی دی',
    'related': 'متعلقہ',
    'relation': 'تعلق',
    'payment': 'ادائیگی',
    'pay': 'ادا کرنا',
    'paid': 'ادا کیا',
    'hush': 'خاموش',
    'illegal': 'غیر قانونی',
    'legal': 'قانونی',
    'legally': 'قانونی طور پر',
    'courtroom': 'عدالت',
    'jury': 'جری',
    'judgment': 'فیصلہ',
    'ruling': 'فیصلہ',
    'order': 'حکم',
    'ordered': 'حکم دیا',
    'ban': 'پابندی',
    'banned': 'پابندی لگا دی',
    'fine': 'جرمانہ',
    'fined': 'جرمانہ عائد',
    'penalty': 'جرمانہ',
    'punishment': 'سزا',
    'investigated': 'تحقیقات کی',
    'question': 'سوال',
    'questioned': 'پوچھ گچھ کی',
    'questioning': 'پوچھ گچھ',
    'interrogate': 'پوچھ گچھ',
    'interrogation': 'پوچھ گچھ',
    'confess': 'اعتراف',
    'confessed': 'اعتراف کیا',
    'confession': 'اعتراف جرم',
    'admit': 'تسلیم کرنا',
    'admitted': 'تسلیم کیا',
    'denial': 'انکار',
    'liability': 'ذمہ داری',
    'responsible': 'ذمہ دار',
    'accountable': 'جوابدہ',
    'oversight': 'نگرانی',
    'supervision': 'نگرانی',
    'monitor': 'نگرانی',
    'monitoring': 'نگرانی',
    'review': 'جائزہ',
    'reviewed': 'جائزہ لیا',
    'audit': 'آڈٹ',
    'scrutiny': 'جانچ پڑتال',
    'regulation': 'ضابطہ',
    'regulatory': 'ضابطہ کاری',
    'comply': 'تعمیل',
    'compliance': 'تعمیل',
    'violation': 'خلاف ورزی',
    'violate': 'خلاف ورزی',
    'violated': 'خلاف ورزی کی',
    'restriction': 'پابندی',
    'restrict': 'محدود',
    'restricted': 'محدود',
    'limit': 'حد',
    'limited': 'محدود',
    'freeze': 'منجمد',
    'frozen': 'منجمد',
    'block': 'بلاک',
    'blocked': 'بلاک کیا',
    'seize': 'ضبط',
    'seized': 'ضبط کیا',
    'confiscate': 'ضبط',
    'confiscated': 'ضبط کیا',
    'asset': 'اثاثہ',
    'assets': 'اثاثے',
    'property': 'جائیداد',
    'account': 'اکاؤنٹ',
    'accounts': 'اکاؤنٹس',
    'funds': 'فنڈز',
    'money laundering': 'منی لانڈرنگ',
    'corrupt': 'بدعنوان',
    'bribe': 'رشوت',
    'kickback': 'کمیشن',
    'embezzlement': 'خرد برد',
    'fraudulent': 'جعلی',
    'forgery': 'جعلی دستخط',
    'counterfeit': 'جعلی',
    'smuggle': 'سمگل',
    'smuggling': 'سمگلنگ',
    'trafficking': 'سمگلنگ',
    'trafficker': 'سمگلر',
    'gang': 'گروہ',
    'gangster': 'گینگسٹر',
    'mafia': 'مافیا',
    'cartel': 'کارٹل',
    'terrorist': 'دہشت گرد',
    'terrorism': 'دہشت گردی',
    'extremist': 'انتہا پسند',
    'extremism': 'انتہا پسندی',
    'militant': 'عسکریت پسند',
    'radical': 'رادیکال',
    'radicalization': 'رادیکالائزیشن',
    'insurgent': 'باغی',
    'insurgency': 'شورش',
    'rebel': 'باغی',
    'rebellion': 'بغاوت',
    'uprising': 'بغاوت',
    'revolt': 'بغاوت',
    'coup': 'بغاوت',
    'overthrow': 'معزولی',
    'oust': 'معزول',
    'ousted': 'معزول کیا',
    'depose': 'معزول',
    'deposed': 'معزول کیا',
    'exile': 'جلاوطنی',
    'exiled': 'جلاوطن',
    'asylum': 'پناہ',
    'sanctuary': 'پناہ',
    'shelter': 'پناہ',
    'protection': 'تحفظ',
    'protect': 'تحفظ',
    'protected': 'محفوظ',
    'guard': 'گارڈ',
    'guarded': 'محفوظ',
    'safe': 'محفوظ',
    'secure': 'محفوظ',
    'secured': 'محفوظ کیا',
    'peaceful': 'پرامن',
    'peacefully': 'پرامن طریقے سے',
    'truce': 'جنگ بندی',
    'armistice': 'جنگ بندی',
    'negotiate': 'مذاکرات',
    'negotiated': 'مذاکرات کیے',
    'mediate': 'ثالثی',
    'mediation': 'ثالثی',
    'arbitration': 'ثالثی',
    'settle': 'تصفیہ',
    'settlement': 'تصفیہ',
    'resolved': 'حل کیا',
    'solution': 'حل',
    'compromise': 'سمجھوتہ',
    'reconciliation': 'مفاہمت',
    'reconcile': 'مفاہمت',
    'discuss': 'بات چیت',
    'discussed': 'بات چیت کی',
    'consult': 'مشاورت',
    'coordinate': 'ہم آہنگی',
    'coordination': 'ہم آہنگی',
    'cooperation': 'تعاون',
    'cooperate': 'تعاون',
    'collaborate': 'اشتراک',
    'collaboration': 'اشتراک',
    'partnership': 'شراکت داری',
    'partner': 'شراکت دار',
    'ally': 'اتحادی',
    'allies': 'اتحادی',
    'friendly': 'دوستانہ',
    'hostile': 'مخالف',
    'enemy': 'دشمن',
    'rival': 'حریف',
    'rivalry': 'دشمنی',
    'competition': 'مقابلہ',
    'compete': 'مقابلہ',
    'competitor': 'مدمقابل',
    'contest': 'مقابلہ',
    'contender': 'امیدوار',
    'opponent': 'مخالف',
    'adversary': 'مخالف',
    'foe': 'دشمن',
    'friend': 'دوست',
    'supporter': 'حامی',
    'backer': 'حمایتی',
    'advocate': 'وکیل',
    'advocacy': 'وکالت',
    'lobby': 'لابی',
    'lobbying': 'لابی نگ',
    'endorse': 'حمایت',
    'endorsement': 'حمایت',
    'endorsed': 'حمایت کی',
    'supported': 'حمایت کی',
    'backing': 'حمایت',
    'disapprove': 'نامنظوری',
    'consent': 'رضامندی',
    'permission': 'اجازت',
    'permit': 'اجازت',
    'allowed': 'اجازت دی',
    'authorize': 'اختیار دینا',
    'authorized': 'مجاز',
    'authorization': 'اجازت',
    'certify': 'تصدیق',
    'certified': 'مصدقہ',
    'certification': 'تصدیق',
    'license': 'لائسنس',
    'licensed': 'لائسنس یافتہ',
    'registration': 'رجسٹریشن',
    'register': 'رجسٹر',
    'registered': 'رجسٹرڈ',
    'enlist': 'شمولیت',
    'enrolled': 'داخلہ لیا',
    'membership': 'رکنیت',
    'affiliate': 'وابستہ',
    'affiliated': 'وابستہ',
    'subsidiary': 'ذیلی ادارہ',
    'parent': 'والدین',
    'firm': 'فرم',
    'enterprise': 'انٹرپرائز',
    'corporation': 'کارپوریشن',
    'corporate': 'کارپوریٹ',
    'multinational': 'ملٹی نیشنل',
    'conglomerate': 'گروپ',
    'group': 'گروپ',
    'organization': 'تنظیم',
    'organize': 'منظم',
    'organized': 'منظم',
    'institution': 'ادارہ',
    'institutional': 'ادارہ جاتی',
    'foundation': 'فاؤنڈیشن',
    'trust': 'ٹرسٹ',
    'charity': 'خیراتی ادارہ',
    'charitable': 'خیراتی',
    'nonprofit': 'غیر منافع بخش',
    'welfare': 'فلاح و بہبود',
    'social': 'سماجی',
    'communal': 'فرقہ وارانہ',
    'sectarian': 'فرقہ وارانہ',
    'ethnic': 'نسلی',
    'tribal': 'قبائلی',
    'tribe': 'قبیلہ',
    'clan': 'قبیلہ',
    'race': 'نسل',
    'racial': 'نسلی',
    'religious': 'مذہبی',
    'religion': 'مذہب',
    'faith': 'عقیدہ',
    'belief': 'عقیدہ',
    'sect': 'فرقہ',
    'denomination': 'فرقہ',
    'united': 'یونائٹڈ',
    'premier': 'پریمیئر',
    'chelsea': 'چیلسی',
    'arsenal': 'آرسنل',
    'tottenham': 'ٹوٹنہم',
    'liverpool': 'لیورپول',
    'manchester': 'مانچسٹر',
    'barcelona': 'بارسلونا',
    'madrid': 'میڈرڈ',
    'juventus': 'جووینٹس',
    'bayern': 'بائرن',
    'munich': 'میونخ',
    'striker': 'سٹرائیکر',
    'manager': 'مینیجر',
    'forward': 'فارورڈ',
    'defender': 'ڈیفنڈر',
    'midfielder': 'مڈفیلڈر',
    'goalkeeper': 'گول کیپر',
    'quarter': 'کوارٹر',
    'semi': 'سیمی',
    'finals': 'فائنلز',
    'derby': 'ڈربی',
    'announced': 'اعلان کیا',
    'beats': 'شکست دیتا ہے',
    'strikes': 'حملہ کرتا ہے',
    'reserves': 'ذخائر',
    'increases': 'اضافہ ہوتا ہے',
    'falls': 'گرتا ہے',
    'falling': 'گرتا ہوا',
    'rising': 'بڑھتا ہوا',
    'highest': 'سب سے زیادہ',
    'lowest': 'سب سے کم',
    'weekly': 'ہفتہ وار',
    'monthly': 'ماہانہ',
    'yearly': 'سالانہ',
    'historic': 'تاریخی',
    'historical': 'تاریخی',
    'dramatic': 'ڈرامائی',
    'rapid': 'تیز',
    'rapidly': 'تیزی سے',
    'sudden': 'اچانک',
    'suddenly': 'اچانک',
    'immediate': 'فوری',
    'immediately': 'فوری طور پر',
    'direct': 'براہ راست',
    'directly': 'براہ راست',
    'indirect': 'بالواسطہ',
    'indirectly': 'بالواسطہ',
    'average': 'اوسط',
    'minimum': 'کم سے کم',
    'maximum': 'زیادہ سے زیادہ',
    'initial': 'ابتدائی',
    'temporary': 'عارضی',
    'permanent': 'مستقل',
    'voluntary': 'رضاکارانہ',
    'mandatory': 'لازمی',
    'compulsory': 'لازمی',
    'optional': 'اختیاری',
    'virtual': 'ورچوئل',
    'actual': 'حقیقی',
    'theoretical': 'نظریاتی',
    'practical': 'عملی',
    'technical': 'تکنیکی',
    'professional': 'پیشہ ورانہ',
    'personal': 'ذاتی',
    'physical': 'جسمانی',
    'mental': 'دماغی',
    'emotional': 'جذباتی',
    'spiritual': 'روحانی',
    'intellectual': 'دانشورانہ',
    'commercial': 'تجارتی',
    'industrial': 'صنعتی',
    'agricultural': 'زرعی',
    'municipal': 'میونسپل',
    'rural': 'دیہی',
    'urban': 'شہری',
    'amid': 'دوران',
    'reserve': 'ریزرو',
    'fall': 'گراوٹ',
    'rise': 'اضافہ',
    'unchanged': 'برقرار',
    'airstrikes': 'فضائی حملے',
    'opening': 'افتتاحی',
    'case': 'کیس',
    'saint': 'سینٹ',
    'germain': 'جرمین',
    'asia': 'ایشیا',
    'prime': 'وزیراعظم',
    'nation': 'قوم',
    'tonight': 'آج رات',
    'reach': 'پہنچ',
    'highs': 'بلند ترین',
    'lows': 'نیچ ترین',
    'transforming': 'تبدیل کر رہا ہے',
    'transformed': 'تبدیل ہوگیا',
    'healthcare': 'صحت کی دیکھ بھال',
    'adds': 'شامل کرتا ہے',
    'added': 'شامل کیا',
    'comes': 'آتا ہے',
    'takes': 'لیتا ہے',
    'calls': 'بلاتا ہے',
    'plays': 'کھیلتا ہے',
    'shows': 'دکھاتا ہے',
    'makes': 'بناتا ہے',
    'moves': 'منتقل',
    'based': 'کی بنیاد پر',
    'named': 'نامزد',
    'called': 'کہلاتا ہے',
    'known': 'معروف',
    'expected': 'متوقع',
    'believed': 'خیال کیا جاتا ہے',
    'considered': 'سمجھا جاتا ہے',
    'regarded': 'سمجھا جاتا ہے',
    'including': 'بشمول',
    'following': 'بعد میں',
    'heading': 'سرخی',
    'looking': 'دیکھ رہا ہے',
    'leading': 'معروف',
    'working': 'کام کر رہا ہے',
    'meeting': 'میٹنگ',
    'meetings': 'اجلاس',
    'discussions': 'بات چیت',
    'operations': 'آپریشنز',
    'investigations': 'تحقیقات',
    'negotiations': 'مذاکرات',
    'relations': 'تعلقات',
    'countries': 'ممالک',
    'cities': 'شہر',
    'officers': 'افسران',
    'members': 'ارکان',
    'players': 'کھلاڑیوں',
    'supporters': 'حامیوں',
    'residents': 'رہائشیوں',
    'officials': 'سرکاری ذرائع',
    'statements': 'بیانات',
    'agreements': 'معاہدے',
    'projects': 'منصوبے',
    'programs': 'پروگرام',
    'services': 'خدمات',
    'systems': 'نظام',
    'forces': 'افواج',
    'attacks': 'حملے',
    'raids': 'چھاپے',
    'changes': 'تبدیلیاں',
    'issues': 'مسائل',
    'problems': 'مسائل',
    'matters': 'معاملات',
    'concerns': 'خدشات',
    'efforts': 'کوششیں',
    'measures': 'اقدامات',
    'steps': 'اقدامات',
    'reforms': 'اصلاحات',
    'results': 'نتائج',
    'impacts': 'اثرات',
    'effects': 'اثرات',
    'benefits': 'فوائد',
    'challenges': 'چیلنجز',
    'opportunities': 'مواقع',
    'threats': 'خطرات',
    'risks': 'خطرات',
    'causes': 'وجوہات',
    'factors': 'عوامل',
  };
  for (const [en, ur] of Object.entries(manual)) {
    ENGLISH_TO_URDU[en] = ur;
  }
}

buildReverseMap();

function transliterateWord(word: string): string {
  if (!word) return word;
  const lower = word.toLowerCase();
  if (/^[a-z\d]+$/.test(lower) && /\d/.test(lower)) return word;
  const KEEP = new Set([
    'us','uk','un','eu','ai','tv','pc','5g','4g','psl','imf','odi',
    't20','icc','bcci','pcb','fifa','nato','who','wto','uae','usa',
  ]);
  if (KEEP.has(lower)) return lower.toUpperCase();

  const C: Record<string, string> = {
    'b':'ب','c':'ک','d':'ڈ','f':'ف','g':'گ',
    'h':'ہ','j':'ج','k':'ک','l':'ل','m':'م',
    'n':'ن','p':'پ','q':'ق','r':'ر','s':'س',
    't':'ٹ','v':'و','w':'و','x':'کس','z':'ز',
  };

  // Suffix patterns (applied first so they don't interfere with other rules)
  let w = lower;
  w = w.replace(/(?:tion|sion)$/, 'شن');
  w = w.replace(/ture$/, 'چر');
  w = w.replace(/dge$/, 'ج');
  w = w.replace(/ing$/, 'نگ');
  w = w.replace(/(?:ed|ied)$/, 'ڈ');
  w = w.replace(/er$/, 'ر');
  w = w.replace(/ly$/, 'لی');
  w = w.replace(/le$/, 'ل');
  w = w.replace(/([bdfgklmnprstvz])\1/g, '$1');

  // Now process char by char
  const M: [string, string][] = [
    ['th','تھ'], ['ch','چ'], ['sh','ش'],
    ['gh','گھ'], ['ph','ف'], ['qu','ق'],
    ['wh','و'], ['kn','ن'], ['ng','نگ'], ['mb','م'],
    ['oo','و'], ['ee','ی'], ['ea','یا'], ['oa','وا'],
    ['ai','ے'], ['ay','ے'], ['oi','وئ'], ['oy','وئ'],
    ['au','آ'], ['aw','آ'], ['ou','آو'], ['ow','آو'],
    ['ew','یو'], ['ie','ی'], ['ei','ی'],
    ['ua','وا'], ['ue','و'], ['ui','وئ'],
    ['ia','یا'], ['io','یو'],
  ];

  let result = '';
  let i = 0;
  while (i < w.length) {
    let matched = false;
    for (const [pat, rep] of M) {
      if (i + pat.length <= w.length && w.substring(i, i + pat.length) === pat) {
        result += rep; i += pat.length; matched = true; break;
      }
    }
    if (matched) continue;

    const ch = w[i]; i++;
    // Map vowels contextually
    if (ch === 'a') { result += result === '' ? 'ا' : 'ا'; continue; }
    if (ch === 'e') { // silent e - skip unless at start
      if (!result || (i < w.length)) { continue; }
      result += 'ی'; continue;
    }
    if (ch === 'i') { result += 'ی'; continue; }
    if (ch === 'o') { result += 'و'; continue; }
    if (ch === 'u') { result += 'و'; continue; }
    if (ch === 'y') { result += 'ی'; continue; }
    result += C[ch] || ch;
  }

  return result;
}

function stemWord(word: string): string | null {
  const attempts: string[] = [];
  const w = word;
  if (w.endsWith('ies') && w.length > 4) attempts.push(w.slice(0, -3) + 'y');
  if (w.endsWith('ves') && w.length > 4) attempts.push(w.slice(0, -3) + 'f');
  if (/(?:sh|ch|ss|o|x)es$/.test(w) && w.length > 4) attempts.push(w.slice(0, -2));
  if (w.endsWith('s') && !w.endsWith('ss') && w.length > 3) attempts.push(w.slice(0, -1));
  if (w.endsWith('ing') && w.length > 4) {
    let s = w.slice(0, -3);
    attempts.push(s);
    if (s.length > 2 && s.at(-1) === s.at(-2)) attempts.push(s.slice(0, -1));
    if (!s.endsWith('e')) attempts.push(s + 'e');
  }
  if (w.endsWith('ied') && w.length > 4) attempts.push(w.slice(0, -3) + 'y');
  if (w.endsWith('ed') && !w.endsWith('eed') && w.length > 3) {
    let s = w.slice(0, -2);
    attempts.push(s);
    if (!s.endsWith('e')) attempts.push(s + 'e');
  }
  for (const a of attempts) {
    if (a.length > 2 && ENGLISH_TO_URDU[a] !== undefined) return ENGLISH_TO_URDU[a];
  }
  return null;
}

export function translateToUrdu(englishText: string): string {
  const words = englishText.split(/\s+/);
  const result: string[] = [];
  for (const word of words) {
    const clean = word.replace(/[^a-zA-Z0-9\-']/g, '');
    const lower = clean.toLowerCase();
    const urdu = ENGLISH_TO_URDU[lower];
    if (urdu !== undefined) {
      result.push(word.replace(clean, urdu));
    } else {
      const stemmed = stemWord(lower);
      if (stemmed) {
        result.push(word.replace(clean, stemmed));
      } else {
        result.push(word.replace(clean, transliterateWord(clean)));
      }
    }
  }
  return result.filter(Boolean).join(' ');
}

const TWO_LETTER_KEEP = new Set(['ai', 'us', 'uk', 'eu', 'tv', 'pc', 'ceo', 'cfo', 'cto', '5g', '4g', 'psl', 'imf', 'cpec', 'odi', 't20']);

export function extractEnglishKeywords(text: string): string[] {
  const translated = translateToEnglish(text);
  const words = translated.split(/\s+/);
  const wordFreq: Record<string, number> = {};

  const stopWords = new Set([
    'the', 'a', 'an', 'in', 'of', 'to', 'and', 'is', 'are', 'was',
    'for', 'on', 'by', 'with', 'at', 'from', 'as', 'be', 'has', 'had',
    'its', 'but', 'not', 'or',
  ]);

  for (const word of words) {
    const cleaned = word.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
    if (!cleaned || stopWords.has(cleaned)) continue;
    if (cleaned.length < 3 && !TWO_LETTER_KEEP.has(cleaned)) continue;
    wordFreq[cleaned] = (wordFreq[cleaned] || 0) + 1;
  }

  return Object.entries(wordFreq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6)
    .map(([word]) => word);
}
