export const URDU_TO_ENGLISH: Record<string, string> = {
  'پاکستان': 'Pakistan',
  'پاکستانی': 'Pakistani',
  'دنیا': 'world',
  'کھیل': 'sports',
  'کاروبار': 'business',
  'شوبز': 'entertainment',
  'سائنس و ٹیکنالوجی': 'technology',
  'صحت': 'health',
  'تعلیم': 'education',
  'سیاست': 'politics',
  'معیشت': 'economy',
  'کرکٹ': 'cricket',
  'فٹ بال': 'football',
  'فلم': 'movie',
  'موبائل': 'mobile',
  'ایپس': 'apps',
  'وائرس': 'virus',
  'عدالت': 'court',
  'انتخابات': 'election',
  'حکومت': 'government',
  'وزیراعظم': 'prime minister',
  'صدر': 'president',
  'آئی ایم ایف': 'IMF',
  'اسٹاک مارکیٹ': 'stock market',
  'سمارٹ فون': 'smartphone',
  'کیمرہ': 'camera',
  'بینک': 'bank',
  'تعلیمی': 'educational',
  'امتحانات': 'exams',
  'ہسپتال': 'hospital',
  'اداکار': 'actor',
  'گرمی': 'summer heat',
  'موسم': 'weather',
  'درجہ حرارت': 'temperature',
  'برآمدات': 'exports',
  'توانائی': 'energy',
  'تیل': 'oil',
  'قدرتی آفت': 'natural disaster',
  'زلزلہ': 'earthquake',
  'سیلاب': 'flood',
  'بارش': 'rain',
  'اجلاس': 'summit meeting',
  'معاہدہ': 'agreement',
  'امن': 'peace',
  'جنگ بندی': 'ceasefire',
  'جنگ': 'war',
  'فوج': 'army',
  'پولیس': 'police',
  'عدالت عظمی': 'supreme court',
  'جج': 'judge',
  'ووٹ': 'vote',
  'قانون': 'law',
  'منصوبہ': 'project plan',
  'منصوبے': 'project',
  'ترقی': 'development',
  'غربت': 'poverty',
  'تعمیر': 'construction',
  'ریلوے': 'railway',
  'سڑک': 'road highway',
  'پانی': 'water',
  'بجلی': 'electricity',
  'زراعت': 'agriculture farming',
  'فصل': 'crop harvest',
  'اضافہ': 'increase',
  'کمی': 'decrease',
  'شرح': 'rate',
  'متوقع': 'expected',
  'مہنگائی': 'inflation',
  'بجٹ': 'budget',
  'وفاقی': 'federal',
  'تنخواہوں': 'salaries',
  'آمد': 'arrival',
  'گرما': 'summer',
  'سالانہ': 'annual',
  'اداروں': 'institutions',
  'آغاز': 'start',
  'سہولتوں': 'facilities',
  'بہتری': 'improvement',
  'مشہور': 'famous',
  'اعلان': 'announcement',
  'چین': 'China',
  'اقتصادی': 'economic',
  'راہداری': 'corridor',
  'تیزی': 'rapid growth',
  'شیڈول': 'schedule',
  'جاری': 'released ongoing',
  'روپے': 'rupee',
  'قدر': 'value',
  'ڈالر': 'dollar',
  'سستا': 'cheaper',
  'نمایاں': 'significant',
  'ڈرامہ': 'drama',
  'سیریل': 'serial',
  'بھارت': 'India',
  'مقبولیت': 'popularity',
  'حاصل': 'gained',
  'لوک': 'folk',
  'میوزک': 'music',
  'فیسٹیول': 'festival',
  'انعقاد': 'held',
  'فنکاروں': 'artists',
  'شرکت': 'participation',
  'سروس': 'service',
  'اجراء': 'launch',
  'تیاریاں': 'preparations',
  'ڈینگی': 'dengue',
  'بخار': 'fever',
  'بچاؤ': 'prevention',
  'احتیاطی': 'preventive',
  'تدابیر': 'measures',
  'پولیو': 'polio',
  'قطرہ': 'drop',
  'مہم': 'campaign',
  'نصاب': 'curriculum',
  'عملی': 'practical',
  'زندگی': 'life',
  'توجہ': 'focus',
  'طلبہ': 'students',
  'اسکالرشپ': 'scholarship',
  'پروگرام': 'program',
  'پی ایس ایل': 'PSL',
  'انڈیکس': 'index',
  'لیگ': 'league',
  'ٹیم': 'team',
  'کھلاڑیوں': 'players',
  'میچ': 'match',
  'ٹورنامنٹ': 'tournament',
  'سیریز': 'series',
  'شکست': 'defeat',
  'فتح': 'victory',
  'ریکارڈ': 'record',
  'لہر': 'wave',
  'سی پیک': 'CPEC',
  'قومی': 'national',
  'بورڈ': 'board',
  'سروسز': 'services',
  'نیٹ': 'internet',
  'امتحان': 'exam examination',
  'نتیجہ': 'result outcome',
  'پوزیشن': 'position rank',
  'درجہ': 'positiongrade ranking',
  'سرٹیفکیٹ': 'certificate',
  'ڈگری': 'degree',
  'ماسٹر': 'master',
  'ڈاکٹر': 'doctor',
  'انجینئرنگ': 'engineering',
  'میڈیکل': 'medical',
  'فن': 'art fine arts',
  'کاروباری': 'business entrepreneurial',
  'وظیفہ': 'job employment',
  'بیروزگاری': 'unemployment',
  'معاشی': 'economic',
  'مالی': 'financial monetary',
  'خزانہ': 'treasury finance',
  'ٹیکس': 'tax',
  'محصول': 'revenue',
  'خرچ': 'expenditure expense',
  'قرض': 'debt loan',
  'بچت': 'savings',
  'منافع': 'profit',
  'نقصان': 'loss',
  'سرمایہ': 'capital investment',
  'کارخانہ': 'factory industry',
  'پیداوار': 'production output',
  'مانگ': 'demand',
  'رسد': 'supply',
  'اجناس': 'commodities goods',
  'درآمد': 'import',
  'برآمد': 'export',
  'ادھار': 'loan borrowing',
  'شرح سود': 'interest rate',
  'مبادلہ': 'exchange',
  'زر': 'gold money',
  'سون': 'gold',
  'چاندی': 'silver',
  'پیٹرول': 'petrol gasoline',
  'ڈیزل': 'diesel',

  'یورپ': 'Europe',
  'امریکی': 'American US',
  'صدارتی': 'presidential',
  'فلسطین': 'Palestine',
  'اقوام متحدہ': 'United Nations',
  'کوششیں': 'efforts',
  'مصنوعی ذہانت': 'artificial intelligence',
  'شعبے': 'sector',
  'انقلاب': 'revolution',
  'نیا': 'new',
  'نئی': 'new',
  'نئے': 'new',
  'مارکیٹ': 'market',
  'جلد': 'soon',
  'متعارف': 'introduced',
  'تبدیلی': 'change',
  'ملک': 'country',
  'شہر': 'city',
  'وزیر': 'minister',
  'صوبائی': 'provincial',
  'مقامی': 'local',
  'عالمی': 'global',
  'فیصلہ': 'decision',
  'اہم': 'important',
  'بڑے': 'major',
  'کامیاب': 'successful',
  'شامل': 'included',
  'تازہ': 'fresh latest',
  'ترجمان': 'spokesperson',
  'ذرائع': 'sources',
  'غیر ملکی': 'foreign',
  'مقابلہ': 'competition',
  'فعال': 'active',
  'قائم': 'established',
  'واقع': 'occurred',
  'اور': 'and',
  'کے': 'of',
  'میں': 'in',
  'لیے': 'for',
  'سے': 'from',
  'کا': 'of',
  'کی': 'of',
  'کو': 'to',
  'پر': 'on',
  'طے پا گیا': 'finalized',
  'پیش': 'presented',
  'توڑ': 'broke',
  'تیز': 'intensified',
  'انقلابی': 'revolutionary',
  'تیار': 'prepared',
  'کا آغاز': 'started',
  'ہے': 'is',
  'ہیں': 'are',
  'گیا': 'was',
  'گئی': 'was',
  'گئے': 'were',
  'ہو': 'been',
  'خلاف': 'against',
  'ساتھ': 'with',
  'بعد': 'after',
  'قبل': 'before',
  'دوران': 'during',
  'بغیر': 'without',
  'صرف': 'only',
  'ہر': 'every',
  'کچھ': 'some',
  'بہت': 'very',
  'ان': 'these',
  'اس': 'this',
  'ایک': 'one',
  'اور بھی': 'more',
  'دیگر': 'other',
  'مزید': 'further',
  'نے': '',
  'بھی': 'also',
  'ہوا': 'was',
  'ہوئی': 'was',
  'ہوئے': 'were',
  'رہا': 'remained',
  'رہی': 'remained',
  'رہے': 'remained',
  'کیا': 'done',
  'کئے': 'done',
  'دی': 'given',
  'دیا': 'given',
  'دیے': 'given',
  'جا': 'being',
  'گا': 'will',
  'گی': 'will',
  'ہوگا': 'will be',
  'ہوگی': 'will be',
  'ہوں گے': 'will be',
  'سکتا': 'can',
  'سکتی': 'can',
  'سکتے': 'can',
  'چاہیے': 'should',
  'ضروری': 'necessary',
  'ممکن': 'possible',
  'کہ': 'that',
  'جن': 'who',
  'جو': 'which',
  'وہ': 'that',
  'یہ': 'this',
  'آپ': 'you',
  'ہم': 'we',
  'انہوں': 'they',
  'ان کا': 'their',
  'اپنے': 'own',
  'اپنی': 'own',
  'اپنا': 'own',
};

export function translateToEnglish(urduText: string): string {
  let result = urduText;
  const sorted = Object.entries(URDU_TO_ENGLISH).sort((a, b) => b[0].length - a[0].length);
  for (const [urdu, english] of sorted) {
    result = result.replace(new RegExp(urdu, 'g'), english);
  }
  return result;
}

const URDU_REGEX = /[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]/g;

export function translateToCleanEnglish(urduText: string): string {
  const translated = translateToEnglish(urduText);
  return translated.replace(URDU_REGEX, '').replace(/\s+/g, ' ').trim();
}

export const ENGLISH_TO_URDU: Record<string, string> = {};

function buildReverseMap() {
  for (const [urdu, english] of Object.entries(URDU_TO_ENGLISH)) {
    const words = english.toLowerCase().split(/\s+/);
    for (const word of words) {
      if (word.length > 2 && !ENGLISH_TO_URDU[word]) {
        ENGLISH_TO_URDU[word] = urdu;
      }
    }
  }
  const manual: Record<string, string> = {
    'the': '',
    'a': 'ایک',
    'an': 'ایک',
    'is': 'ہے',
    'are': 'ہیں',
    'was': 'تھا',
    'were': 'تھے',
    'be': 'ہو',
    'been': 'ہوا',
    'to': 'کو',
    'of': 'کا',
    'in': 'میں',
    'for': 'کے لیے',
    'on': 'پر',
    'by': 'کی طرف سے',
    'with': 'کے ساتھ',
    'at': 'میں',
    'from': 'سے',
    'and': 'اور',
    'or': 'یا',
    'but': 'لیکن',
    'not': 'نہیں',
    'has': 'رکھتا ہے',
    'have': 'رکھتے ہیں',
    'had': 'تھا',
    'its': 'اس کا',
    'this': 'یہ',
    'that': 'وہ',
    'these': 'یہ',
    'those': 'وہ',
    'it': 'یہ',
    'he': 'وہ',
    'she': 'وہ',
    'they': 'وہ',
    'we': 'ہم',
    'you': 'آپ',
    'will': 'گا',
    'would': 'گا',
    'can': 'سکتا ہے',
    'could': 'سکتا تھا',
    'should': 'چاہیے',
    'may': 'سکتا ہے',
    'might': 'سکتا تھا',
    'do': 'کرتا ہے',
    'does': 'کرتا ہے',
    'did': 'کیا',
    'after': 'کے بعد',
    'before': 'سے پہلے',
    'during': 'کے دوران',
    'over': 'سے زیادہ',
    'under': 'کے نیچے',
    'between': 'کے درمیان',
    'about': 'کے بارے میں',
    'into': 'میں',
    'through': 'کے ذریعے',
    'against': 'کے خلاف',
    'new': 'نیا',
    'old': 'پرانا',
    'more': 'مزید',
    'less': 'کم',
    'many': 'بہت سے',
    'much': 'بہت',
    'some': 'کچھ',
    'any': 'کوئی',
    'all': 'تمام',
    'each': 'ہر',
    'every': 'ہر',
    'other': 'دوسرے',
    'such': 'ایسا',
    'no': 'نہیں',
    'own': 'اپنا',
    'very': 'بہت',
    'just': 'صرف',
    'also': 'بھی',
    'only': 'صرف',
    'now': 'اب',
    'then': 'پھر',
    'here': 'یہاں',
    'there': 'وہاں',
    'when': 'جب',
    'where': 'جہاں',
    'why': 'کیوں',
    'how': 'کیسے',
    'what': 'کیا',
    'which': 'جو',
    'who': 'جو',
    'whom': 'جسے',
    'whose': 'جس کا',
    'if': 'اگر',
    'than': 'سے',
    'so': 'تو',
    'as': 'جبکہ',
    'while': 'جبکہ',
    'though': 'اگرچہ',
    'because': 'کیونکہ',
    'up': 'اوپر',
    'down': 'نیچے',
    'out': 'باہر',
    'off': 'بند',
    'away': 'دور',
    'back': 'واپس',
    'still': 'اب بھی',
    'yet': 'ابھی تک',
    'already': 'پہلے ہی',
    'ever': 'کبھی',
    'never': 'کبھی نہیں',
    'always': 'ہمیشہ',
    'often': 'اکثر',
    'sometimes': 'کبھی کبھی',
    'usually': 'عام طور پر',
    'once': 'ایک بار',
    'again': 'پھر',
    'well': 'اچھی طرح',
    'even': 'یہاں تک کہ',
    'really': 'واقعی',
    'quite': 'کافی',
    'enough': 'کافی',
    'rather': 'بلکہ',
    'around': 'ارد گرد',
    'along': 'کے ساتھ ساتھ',
    'among': 'کے درمیان',
    'beyond': 'سے باہر',
    'without': 'بغیر',
    'within': 'کے اندر',
    'across': 'بھر میں',
    'despite': 'کے باوجود',
    'since': 'سے',
    'until': 'تک',
    'upon': 'پر',
    'via': 'کے ذریعے',
    'per': 'فی',
    'toward': 'کی طرف',
    'like': 'جیسے',
    'unlike': 'کے برعکس',
    'top': 'سب سے اوپر',
    'behind': 'پیچھے',
    'ahead': 'آگے',
    'next': 'اگلا',
    'last': 'آخری',
    'first': 'پہلا',
    'second': 'دوسرا',
    'third': 'تیسرا',
    'latest': 'تازہ ترین',
    'breaking': 'بریکنگ',
    'live': 'لائیو',
    'update': 'اپ ڈیٹ',
    'report': 'رپورٹ',
    'watch': 'دیکھیں',
    'video': 'ویڈیو',
    'photo': 'تصویر',
    'picture': 'تصویر',
    'image': 'تصویر',
    'world': 'دنیا',
    'global': 'عالمی',
    'international': 'بین الاقوامی',
    'local': 'مقامی',
    'national': 'قومی',
    'regional': 'علاقائی',
    'city': 'شہر',
    'country': 'ملک',
    'people': 'لوگ',
    'official': 'سرکاری',
    'president': 'صدر',
    'minister': 'وزیر',
    'government': 'حکومت',
    'police': 'پولیس',
    'court': 'عدالت',
    'judge': 'جج',
    'law': 'قانون',
    'election': 'انتخابات',
    'vote': 'ووٹ',
    'political': 'سیاسی',
    'party': 'جماعت',
    'leader': 'رہنما',
    'attack': 'حملہ',
    'killed': 'ہلاک',
    'dead': 'مرنے والے',
    'injured': 'زخمی',
    'death': 'موت',
    'hospital': 'ہسپتال',
    'doctor': 'ڈاکٹر',
    'health': 'صحت',
    'disease': 'بیماری',
    'treatment': 'علاج',
    'drug': 'دوا',
    'vaccine': 'ویکسین',
    'covid': 'کوویڈ',
    'coronavirus': 'کورونا وائرس',
    'pandemic': 'وبا',
    'climate': 'آب و ہوا',
    'weather': 'موسم',
    'temperature': 'درجہ حرارت',
    'earthquake': 'زلزلہ',
    'flood': 'سیلاب',
    'rain': 'بارش',
    'storm': 'طوفان',
    'disaster': 'آفت',
    'crisis': 'بحران',
    'war': 'جنگ',
    'peace': 'امن',
    'russian': 'روسی',
    'american': 'امریکی',
    'britain': 'برطانیہ',
    'british': 'برطانوی',
    'france': 'فرانس',
    'french': 'فرانسیسی',
    'germany': 'جرمنی',
    'german': 'جرمن',
    'japanese': 'جاپانی',
    'ukraine': 'یوکرین',
    'ukrainian': 'یوکرینی',
    'australia': 'آسٹریلیا',
    'australian': 'آسٹریلوی',
    'canada': 'کینیڈا',
    'canadian': 'کینیڈین',
    'washington': 'واشنگٹن',
    'london': 'لندن',
    'paris': 'پیرس',
    'moscow': 'ماسکو',
    'beijing': 'بیجنگ',
    'kabul': 'کابل',
    'tehran': 'تہران',
    'baghdad': 'بغداد',
    'cairo': 'قاہرہ',
    'islamabad': 'اسلام آباد',
    'karachi': 'کراچی',
    'lahore': 'لاہور',
    'gaza': 'غزہ',
    'jerusalem': 'یروشلم',
    'dubai': 'دبئی',
    'nato': 'نیٹو',
    'hamas': 'حماس',
    'hezbollah': 'حزب اللہ',
    'taliban': 'طالبان',
    'pentagon': 'پینٹاگن',
    'trump': 'ٹرمپ',
    'biden': 'بائیڈن',
    'putin': 'پیوٹن',
    'zelensky': 'زیلنسکی',
    'netanyahu': 'نیتن یاہو',
    'modi': 'مودی',
    'khan': 'خان',
    'st petersburg': 'سینٹ پیٹرزبرگ',
    'cafe': 'کیفے',
    'suspects': 'ملزمان',
    'bombings': 'بم دھماکے',
    'authorities': 'حکام',
    'says': 'کہتے ہیں',
    'sources': 'ذرائع',
    'source': 'ماخذ',
    'according': 'مطابق',
    'struck': 'حملہ کیا',
    'iranian': 'ایرانی',
    'radar': 'ریڈار',
    'sites': 'مقامات',
    'kuwait': 'کویت',
    'reports': 'رپورٹیں',
    'missiles': 'میزائل',
    'drones': 'ڈرون',
    'rugby': 'رگبی',
    'legend': 'افسانہ',
    'broadcaster': 'بروڈکاسٹر',
    'dies': 'انتقال کر گئے',
    'aged': 'عمر',
    'later': 'بعد میں',
    'soon': 'جلد',
    'earlier': 'پہلے',
    'currently': 'فی الحال',
    'ongoing': 'جاری',
    'updated': 'اپ ڈیٹ شدہ',
    'exclusive': 'خصوصی',
    'editorial': 'اداریہ',
    'feature': 'فیچر',
    'coverage': 'کوریج',
    'developing': 'تیار ہونے والی',
    'reportedly': 'بتایا جاتا ہے',
    'unconfirmed': 'غیر مصدقہ',
    'several': 'کئی',
    'multiple': 'متعدد',
    'massive': 'بڑے پیمانے پر',
    'entire': 'پورا',
    'total': 'کل',
    'floods': 'سیلاب',
    'million': 'ملین',
    'billion': 'ارب',
    'thousand': 'ہزار',
    'percent': 'فیصد',
    'patients': 'مریض',
    'recover': 'صحت یابی',
    'recovered': 'صحت یاب',
    'defeated': 'شکست دی',
    'won': 'جیت لیا',
    'lost': 'ہار گیا',
    'champion': 'چیمپئن',
    'champions': 'چیمپئن',
    'markets': 'مارکیٹیں',
    'stocks': 'اسٹاک',
    'profits': 'منافع',
    'losses': 'نقصانات',
    'loans': 'قرضے',
    'taxes': 'ٹیکس',
    'tariffs': 'ٹیرف',
    'exports': 'برآمدات',
    'imports': 'درآمدات',
    'investments': 'سرمایہ کاری',
    'investors': 'سرمایہ کار',
    'companies': 'کمپنیاں',
    'banks': 'بینک',
    'banking': 'بینکنگ',
    'unemployment': 'بے روزگاری',
    'employment': 'روزگار',
    'schools': 'سکول',
    'students': 'طلباء',
    'teachers': 'اساتذہ',
    'artificial': 'مصنوعی',
    'crime': 'جرم',
    'crimes': 'جرائم',
    'criminal': 'مجرم',
    'terror': 'دہشت',
    'protests': 'احتجاجات',
    'elections': 'انتخابات',
    'voting': 'رائے شماری',
    'governor': 'گاورنر',
    'presidential': 'صدراتی',
    'prime minister': 'وزیراعظم',
    'parliamentary': 'پارلیمینٹری',
    'leaders': 'رہنماء',
    'speaker': 'سپیکر',
    'soldiers': 'فوجی',
    'ceasefire': 'جنگ بندی',
    'military': 'فوجی',
    'army': 'فوج',
    'soldier': 'فوجی',
    'india': 'بھارت',
    'pakistan': 'پاکستان',
    'america': 'امریکہ',
    'us': 'امریکہ',
    'uk': 'برطانیہ',
    'europe': 'یورپ',
    'russia': 'روس',
    'iran': 'ایران',
    'afghanistan': 'افغانستان',
    'palestine': 'فلسطین',
    'israel': 'اسرائیل',
    'turkey': 'ترکی',
    'saudi': 'سعودی',
    'china': 'چین',
    'japan': 'جاپان',
    'kashmir': 'کشمیر',
    'sports': 'کھیل',
    'football': 'فٹ بال',
    'cricket': 'کرکٹ',
    'tennis': 'ٹینس',
    'hockey': 'ہاکی',
    'olympic': 'اولمپک',
    'match': 'میچ',
    'game': 'کھیل',
    'player': 'کھلاڑی',
    'team': 'ٹیم',
    'coach': 'کوچ',
    'tournament': 'ٹورنامنٹ',
    'championship': 'چیمپئن شپ',
    'league': 'لیگ',
    'final': 'فائنل',
    'win': 'جیت',
    'loss': 'ہار',
    'score': 'سکور',
    'goal': 'گول',
    'business': 'کاروبار',
    'economy': 'معیشت',
    'market': 'مارکیٹ',
    'stock': 'اسٹاک',
    'bank': 'بینک',
    'money': 'پیسہ',
    'dollar': 'ڈالر',
    'rupee': 'روپے',
    'price': 'قیمت',
    'rate': 'شرح',
    'trade': 'تجارت',
    'export': 'برآمد',
    'import': 'درآمد',
    'tax': 'ٹیکس',
    'budget': 'بجٹ',
    'debt': 'قرض',
    'loan': 'قرض',
    'inflation': 'مہنگائی',
    'profit': 'منافع',
    'company': 'کمپنی',
    'industry': 'صنعت',
    'technology': 'ٹیکنالوجی',
    'tech': 'ٹیک',
    'digital': 'ڈیجیٹل',
    'internet': 'انٹرنیٹ',
    'phone': 'فون',
    'mobile': 'موبائل',
    'computer': 'کمپیوٹر',
    'software': 'سافٹ ویئر',
    'app': 'ایپ',
    'data': 'ڈیٹا',
    'ai': 'AI',
    'robot': 'روبوٹ',
    'space': 'خلاء',
    'science': 'سائنس',
    'research': 'تحقیق',
    'education': 'تعلیم',
    'school': 'سکول',
    'university': 'یونیورسٹی',
    'college': 'کالج',
    'student': 'طالب علم',
    'teacher': 'استاد',
    'exam': 'امتحان',
    'result': 'نتیجہ',
    'entertainment': 'تفریح',
    'movie': 'فلم',
    'film': 'فلم',
    'music': 'موسیقی',
    'song': 'گیت',
    'actor': 'اداکار',
    'actress': 'اداکارہ',
    'singer': 'گلوکار',
    'drama': 'ڈرامہ',
    'show': 'شو',
    'festival': 'تہوار',
    'award': 'ایوارڈ',
    'celebrity': 'مشہور شخصیت',
    'famous': 'مشہور',
    'culture': 'ثقافت',
    'art': 'فن',
    'book': 'کتاب',
    'writer': 'مصنف',
    'author': 'مصنف',
    'news': 'خبر',
    'media': 'میڈیا',
    'press': 'پریس',
    'journalist': 'صحافی',
    'editor': 'ایڈیٹر',
    'publish': 'شائع',
    'article': 'مضمون',
    'headline': 'سرخی',
    'story': 'کہانی',
    'hour': 'گھنٹہ',
    'day': 'دن',
    'week': 'ہفتہ',
    'month': 'مہینہ',
    'year': 'سال',
    'today': 'آج',
    'yesterday': 'کل',
    'tomorrow': 'کل',
    'morning': 'صبح',
    'evening': 'شام',
    'night': 'رات',
    'time': 'وقت',
    'date': 'تاریخ',
    'minute': 'منٹ',
    'ago': 'پہلے',
    'early': 'ابتدائی',
    'late': 'دیر',
    'recent': 'حالیہ',
    'current': 'موجودہ',
    'previous': 'گزشتہ',
    'coming': 'آنے والا',
    'upcoming': 'آنے والا',
    'future': 'مستقبل',
    'past': 'ماضی',
    'young': 'جوان',
    'modern': 'جدید',
    'traditional': 'روایتی',
    'major': 'اہم',
    'minor': 'معمولی',
    'key': 'اہم',
    'chief': 'سربراہ',
    'main': 'اہم',
    'primary': 'بنیادی',
    'senior': 'سینئر',
    'junior': 'جونیئر',
    'lead': 'قیادت',
    'important': 'اہم',
    'significant': 'اہم',
    'crucial': 'اہم',
    'critical': 'نازک',
    'vital': 'ضروری',
    'essential': 'ضروری',
    'necessary': 'ضروری',
    'possible': 'ممکن',
    'potential': 'ممکنہ',
    'likely': 'ممکنہ',
    'special': 'خصوصی',
    'general': 'جنرل',
    'specific': 'مخصوص',
    'particular': 'خاص',
    'individual': 'انفرادی',
    'public': 'عوام',
    'private': 'نجی',
    'domestic': 'ملکی',
    'foreign': 'غیر ملکی',
    'external': 'بیرونی',
    'internal': 'داخلی',
    'central': 'مرکزی',
    'federal': 'وفاقی',
    'provincial': 'صوبائی',
    'state': 'ریاست',
    'province': 'صوبہ',
    'district': 'ضلع',
    'capital': 'دارالحکومت',
    'parliament': 'پارلیمنٹ',
    'senate': 'سینیٹ',
    'assembly': 'اسمبلی',
    'congress': 'کانگریس',
    'opposition': 'اپوزیشن',
    'alliance': 'اتحاد',
    'coalition': 'اتحاد',
    'member': 'رکن',
    'chairman': 'چیئرمین',
    'secretary': 'سیکرٹری',
    'spokesman': 'ترجمان',
    'spokesperson': 'ترجمان',
    'authority': 'اختیار',
    'department': 'محکمہ',
    'ministry': 'وزارت',
    'agency': 'ایجنسی',
    'commission': 'کمیشن',
    'committee': 'کمیٹی',
    'council': 'کونسل',
    'board': 'بورڈ',
    'bureau': 'بیورو',
    'session': 'اجلاس',
    'summit': 'سربراہی اجلاس',
    'conference': 'کانفرنس',
    'dialogue': 'مذاکرات',
    'negotiation': 'مذاکرات',
    'talks': 'مذاکرات',
    'deal': 'معاہدہ',
    'agreement': 'معاہدہ',
    'treaty': 'معاہدہ',
    'pact': 'معاہدہ',
    'accord': 'معاہدہ',
    'bill': 'بل',
    'act': 'ایکٹ',
    'ordinance': 'آرڈیننس',
    'resolution': 'قرارداد',
    'amendment': 'ترمیم',
    'constitution': 'آئین',
    'constitutional': 'آئینی',
    'supreme': 'سپریم',
    'justice': 'انصاف',
    'chief justice': 'چیف جسٹس',
    'hearing': 'سماعت',
    'verdict': 'فیصلہ',
    'sentence': 'سزا',
    'appeal': 'اپیل',
    'petition': 'درخواست',
    'plea': 'درخواست',
    'charge': 'الزام',
    'accusation': 'الزام',
    'allegation': 'الزام',
    'evidence': 'ثبوت',
    'witness': 'گواہ',
    'trial': 'مقدمہ',
    'prosecution': 'استغاثہ',
    'defense': 'دفاع',
    'defendant': 'ملزم',
    'suspect': 'ملزم',
    'accused': 'ملزم',
    'arrest': 'گرفتاری',
    'detain': 'حراست',
    'bail': 'ضمانت',
    'prison': 'جیل',
    'jail': 'جیل',
    'release': 'رہائی',
    'convict': 'مجرم',
    'guilty': 'مجرم',
    'innocent': 'بے قصور',
    'investigation': 'تحقیقات',
    'inquiry': 'انکوائری',
    'probe': 'تحقیقات',
    'investigate': 'تحقیقات کرنا',
    'protest': 'احتجاج',
    'rally': 'ریلی',
    'march': 'مارچ',
    'demonstration': 'مظاہرہ',
    'protesters': 'مظاہرین',
    'strike': 'ہڑتال',
    'boycott': 'بائیکاٹ',
    'campaign': 'مہم',
    'policy': 'پالیسی',
    'reform': 'اصلاحات',
    'development': 'ترقی',
    'progress': 'ترقی',
    'growth': 'ترقی',
    'plan': 'منصوبہ',
    'project': 'منصوبہ',
    'program': 'پروگرام',
    'scheme': 'اسکیم',
    'initiative': 'اقدام',
    'strategy': 'حکمت عملی',
    'system': 'نظام',
    'process': 'عمل',
    'operation': 'آپریشن',
    'mission': 'مشن',
    'candidate': 'امیدوار',
    'ballot': 'بیلٹ',
    'poll': 'رائے شماری',
    'seat': 'نشست',
    'constituency': 'حلقہ',
    'term': 'مدت',
    'tenure': 'مدت',
    'resign': 'استعفیٰ',
    'resignation': 'استعفیٰ',
    'dismiss': 'برطرف',
    'suspend': 'معطل',
    'removal': 'برطرفی',
    'appoint': 'تقرری',
    'appointment': 'تقرری',
    'nominate': 'نامزد',
    'nomination': 'نامزدگی',
    'elect': 'منتخب',
    'elected': 'منتخب',
    'corruption': 'بدعنوانی',
    'scandal': 'اسکینڈل',
    'fraud': 'دھوکہ دہی',
    'bribery': 'رشوت',
    'nepotism': 'سفارش',
    'accountability': 'احتساب',
    'transparency': 'شفافیت',
    'address': 'خطاب',
    'speech': 'تقریر',
    'statement': 'بیان',
    'announcement': 'اعلان',
    'declaration': 'اعلان',
    'press conference': 'پریس کانفرنس',
    'briefing': 'بریفنگ',
    'interview': 'انٹرویو',
    'debate': 'بحث',
    'discussion': 'بات چیت',
    'consultation': 'مشاورت',
    'interaction': 'بات چیت',
    'communication': 'مواصلات',
    'message': 'پیغام',
    'response': 'جواب',
    'reply': 'جواب',
    'reaction': 'ردعمل',
    'suggestion': 'تجاویز',
    'recommendation': 'سفارش',
    'proposal': 'تجویز',
    'demand': 'مطالبہ',
    'request': 'درخواست',
    'call': 'مطالبہ',
    'urge': 'زور دینا',
    'urged': 'زور دیا',
    'ask': 'پوچھنا',
    'asked': 'پوچھا',
    'tell': 'بتانا',
    'told': 'بتایا',
    'say': 'کہنا',
    'said': 'کہا',
    'add': 'شامل کرنا',
    'confirm': 'تصدیق',
    'confirmed': 'تصدیق شدہ',
    'reveal': 'انکشاف',
    'revealed': 'انکشاف ہوا',
    'announce': 'اعلان',
    'declare': 'اعلان',
    'declared': 'اعلان کیا',
    'stated': 'بیان کیا',
    'reported': 'رپورٹ کیا',
    'claim': 'دعویٰ',
    'claimed': 'دعویٰ کیا',
    'allege': 'الزام لگانا',
    'alleged': 'الزامی',
    'accuse': 'الزام لگانا',
    'blame': 'الزام',
    'blamed': 'الزام لگایا',
    'praise': 'تعریف',
    'praised': 'تعریف کی',
    'criticize': 'تنقید',
    'criticized': 'تنقید کی',
    'criticism': 'تنقید',
    'condemn': 'مذمت',
    'condemned': 'مذمت کی',
    'denounce': 'مذمت',
    'denounced': 'مذمت کی',
    'reject': 'مسترد',
    'rejected': 'مسترد کیا',
    'accept': 'قبول',
    'accepted': 'قبول کیا',
    'approve': 'منظور',
    'approved': 'منظور شدہ',
    'approval': 'منظوری',
    'deny': 'انکار',
    'denied': 'انکار کیا',
    'refuse': 'انکار',
    'refused': 'انکار کیا',
    'agree': 'اتفاق',
    'agreed': 'اتفاق کیا',
    'sign': 'دستخط',
    'signed': 'دستخط شدہ',
    'signing': 'دستخط',
    'launch': 'شروع',
    'launched': 'شروع کیا',
    'start': 'شروع',
    'started': 'شروع ہوا',
    'begin': 'شروع',
    'began': 'شروع ہوا',
    'end': 'ختم',
    'ended': 'ختم ہوا',
    'stop': 'روکنا',
    'stopped': 'روک دیا',
    'continue': 'جاری',
    'continued': 'جاری رہا',
    'remain': 'رہنا',
    'remained': 'رہا',
    'keep': 'رکھنا',
    'kept': 'رکھا',
    'set': 'مقرر',
    'make': 'بنانا',
    'made': 'بنایا',
    'take': 'لینا',
    'took': 'لیا',
    'give': 'دینا',
    'gave': 'دیا',
    'put': 'رکھنا',
    'hold': 'منعقد',
    'held': 'منعقد کیا',
    'propose': 'تجویز',
    'proposed': 'تجویز کردہ',
    'suggest': 'مشورہ',
    'suggested': 'مشورہ دیا',
    'warn': 'انتباہ',
    'warned': 'انتباہ کیا',
    'warning': 'انتباہ',
    'threat': 'دھمکی',
    'threaten': 'دھمکی دینا',
    'threatened': 'دھمکی دی',
    'force': 'طاقت',
    'navy': 'بحریہ',
    'air force': 'فضائیہ',
    'marine': 'میرین',
    'troops': 'فوجی',
    'security': 'سیکورٹی',
    'intelligence': 'انٹیلی جنس',
    'surveillance': 'نگرانی',
    'attacked': 'حملہ کیا',
    'raid': 'چھاپہ',
    'assault': 'حملہ',
    'ambush': 'گھات لگانا',
    'blast': 'دھماکہ',
    'explosion': 'دھماکہ',
    'explode': 'دھماکہ',
    'bomb': 'بم',
    'bombing': 'بم دھماکہ',
    'missile': 'میزائل',
    'drone': 'ڈرون',
    'rocket': 'راکٹ',
    'shelling': 'گولہ باری',
    'firing': 'فائرنگ',
    'gunfire': 'گولی باری',
    'shooting': 'فائرنگ',
    'gunshot': 'گولی',
    'bullet': 'گولی',
    'weapon': 'ہتھیار',
    'arms': 'اسلحہ',
    'nuclear': 'جوہری',
    'atomic': 'ایٹمی',
    'suicide': 'خودکش',
    'suicide bomb': 'خودکش بم',
    'target': 'ہدف',
    'targeted': 'ہدف بنایا',
    'destroy': 'تباہ',
    'destroyed': 'تباہ ہوگیا',
    'damage': 'نقصان',
    'damaged': 'نقصان پہنچا',
    'casualty': 'ہلاکت',
    'casualties': 'ہلاکتیں',
    'deaths': 'اموات',
    'died': 'مر گیا',
    'kill': 'مارنا',
    'murder': 'قتل',
    'murdered': 'قتل کیا',
    'injure': 'زخمی',
    'wound': 'زخم',
    'wounded': 'زخمی',
    'victim': 'متاثرہ',
    'victims': 'متاثرین',
    'survivor': 'زندہ بچنے والا',
    'rescue': 'ریسکیو',
    'rescued': 'بچایا گیا',
    'relief': 'امدادی',
    'aid': 'امداد',
    'assistance': 'مدد',
    'support': 'حمایت',
    'help': 'مدد',
    'donation': 'عطیہ',
    'fund': 'فنڈ',
    'funding': 'فنڈنگ',
    'grant': 'گرانٹ',
    'package': 'پیکیج',
    'emergency': 'ایمرجنسی',
    'conflict': 'تنازعہ',
    'dispute': 'تنازعہ',
    'tension': 'کشیدگی',
    'violence': 'تشدد',
    'bloodshed': 'خون ریزی',
    'massacre': 'قتل عام',
    'atrocity': 'ظلم',
    'genocide': 'نسل کشی',
    'humanitarian': 'انسانی ہمدردی',
    'refugee': 'پناہ گزین',
    'migrant': 'مہاجر',
    'displaced': 'بے گھر',
    'border': 'سرحد',
    'boundary': 'حدود',
    'territory': 'علاقہ',
    'region': 'علاقہ',
    'sector': 'سیکٹر',
    'zone': 'زون',
    'area': 'علاقہ',
    'economic': 'اقتصادی',
    'financial': 'مالی',
    'fiscal': 'مالی',
    'monetary': 'مالیاتی',
    'deficit': 'خسارہ',
    'surplus': 'سرپلس',
    'revenue': 'آمدنی',
    'income': 'آمدنی',
    'salary': 'تنخواہ',
    'wage': 'اجرت',
    'pension': 'پنشن',
    'benefit': 'فائدہ',
    'taxation': 'ٹیکسیشن',
    'tariff': 'ٹیرف',
    'custom': 'کسٹم',
    'duty': 'ڈیوٹی',
    'investment': 'سرمایہ کاری',
    'investor': 'سرمایہ کار',
    'interest': 'سود',
    'cost': 'لاگت',
    'value': 'قدر',
    'exchange': 'ایکسچینج',
    'currency': 'کرنسی',
    'euro': 'یورو',
    'pound': 'پاؤنڈ',
    'gold': 'سونا',
    'silver': 'چاندی',
    'oil': 'تیل',
    'petroleum': 'پیٹرولیم',
    'gas': 'گیس',
    'petrol': 'پیٹرول',
    'diesel': 'ڈیزل',
    'energy': 'توانائی',
    'power': 'بجلی',
    'electricity': 'بجلی',
    'shortage': 'قلت',
    'supply': 'فراہمی',
    'consumption': 'کھپت',
    'production': 'پیداوار',
    'manufacturing': 'مینوفیکچرنگ',
    'factory': 'کارخانہ',
    'plant': 'پلانٹ',
    'infrastructure': 'انفراسٹرکچر',
    'construction': 'تعمیرات',
    'road': 'سڑک',
    'bridge': 'پل',
    'highway': 'ہائی وے',
    'motorway': 'موٹر وے',
    'railway': 'ریلوے',
    'airport': 'ہوائی اڈہ',
    'port': 'بندرگاہ',
    'tunnel': 'سرنگ',
    'dam': 'ڈیم',
    'canal': 'نہر',
    'river': 'دریا',
    'water': 'پانی',
    'agriculture': 'زراعت',
    'farming': 'کاشتکاری',
    'crop': 'فصل',
    'food': 'غذا',
    'wheat': 'گندم',
    'rice': 'چاول',
    'cotton': 'کپاس',
    'sugar': 'چینی',
    'fertilizer': 'کھاد',
    'medical': 'طبی',
    'clinic': 'کلینک',
    'nurse': 'نرس',
    'patient': 'مریض',
    'illness': 'بیماری',
    'infection': 'انفیکشن',
    'virus': 'وائرس',
    'bacteria': 'بیکٹیریا',
    'symptom': 'علامت',
    'test': 'ٹیسٹ',
    'diagnosis': 'تشخیص',
    'therapy': 'تھراپی',
    'medicine': 'دوا',
    'vaccination': 'ویکسینیشن',
    'dose': 'خوراک',
    'surgery': 'سرجری',
    'transplant': 'ٹرانسپلانٹ',
    'organ': 'عضو',
    'blood': 'خون',
    'cancer': 'کینسر',
    'diabetes': 'ذیابیطس',
    'heart': 'دل',
    'brain': 'دماغ',
    'lungs': 'پھیپھڑے',
    'kidney': 'گردہ',
    'liver': 'جگر',
    'pregnancy': 'حمل',
    'birth': 'پیدائش',
    'mortality': 'اموات',
    'epidemic': 'وبا',
    'outbreak': 'پھیلنا',
    'quarantine': 'قرنطینہ',
    'lockdown': 'لاک ڈاؤن',
    'safety': 'حفاظت',
    'educational': 'تعلیمی',
    'institute': 'انسٹی ٹیوٹ',
    'academy': 'اکیڈمی',
    'professor': 'پروفیسر',
    'lecturer': 'لیکچرر',
    'lecture': 'لیکچر',
    'class': 'کلاس',
    'classroom': 'کلاس روم',
    'course': 'کورس',
    'degree': 'ڈگری',
    'diploma': 'ڈپلومہ',
    'scholarship': 'اسکالرشپ',
    'admission': 'داخلہ',
    'enrollment': 'اندراج',
    'examination': 'امتحان',
    'grade': 'گریڈ',
    'marks': 'نمبر',
    'curriculum': 'نصاب',
    'syllabus': 'نصاب',
    'online': 'آن لائن',
    'cyber': 'سائبر',
    'hardware': 'ہارڈ ویئر',
    'smartphone': 'اسمارٹ فون',
    'network': 'نیٹ ورک',
    'satellite': 'سیٹلائٹ',
    'sport': 'کھیل',
    'captain': 'کپتان',
    'cup': 'کپ',
    'trophy': 'ٹرافی',
    'medal': 'تمغہ',
    'bronze': 'کانسی',
    'victory': 'فتح',
    'defeat': 'شکست',
    'draw': 'برابری',
    'run': 'رن',
    'wicket': 'وکٹ',
    'ball': 'گیند',
    'bat': 'بیٹ',
    'bowl': 'گیند بازی',
    'stadium': 'اسٹیڈیم',
    'ground': 'میدان',
    'field': 'میدان',
    'practice': 'مشق',
    'training': 'تربیت',
    'world cup': 'ورلڈ کپ',
    'semi final': 'سیمی فائنل',
    'quarter final': 'کوارٹر فائنل',
    'rainfall': 'بارش',
    'flooding': 'سیلاب',
    'drought': 'خشک سالی',
    'hurricane': 'سمندری طوفان',
    'tornado': 'طوفان',
    'cyclone': 'طوفان',
    'typhoon': 'طوفان',
    'tremor': 'زلزلہ',
    'snow': 'برف',
    'snowfall': 'برف باری',
    'heat': 'گرمی',
    'heatwave': 'گرمی کی لہر',
    'cold': 'سردی',
    'cold wave': 'سردی کی لہر',
    'wind': 'ہوا',
    'air': 'ہوا',
    'environment': 'ماحول',
    'pollution': 'آلودگی',
    'smog': 'سموگ',
    'carbon': 'کاربن',
    'emission': 'اخراج',
    'forest': 'جنگل',
    'wildlife': 'جنگلی حیات',
    'animal': 'جانور',
    'bird': 'پرندہ',
    'species': 'نوعیت',
    'natural': 'قدرتی',
    'conservation': 'تحفظ',
    'showbiz': 'شوبز',
    'cinema': 'سنیمہ',
    'serial': 'سیریل',
    'director': 'ہدایتکار',
    'producer': 'پروڈیوسر',
    'poet': 'شاعر',
    'artist': 'فنکار',
    'painter': 'مصور',
    'celebration': 'جشن',
    'ceremony': 'تقریب',
    'event': 'تقریب',
    'function': 'تقریب',
    'performance': 'پرفارمنس',
    'stage': 'اسٹیج',
    'concert': 'کنسرٹ',
    'prize': 'انعام',
    'heritage': 'ورثہ',
    'tradition': 'روایت',
    'fashion': 'فیشن',
    'design': 'ڈیزائن',
    'beauty': 'خوبصورتی',
    'issue': 'مسئلہ',
    'problem': 'مسئلہ',
    'matter': 'معاملہ',
    'concern': 'تشویش',
    'challenge': 'چیلنج',
    'risk': 'خطرہ',
    'danger': 'خطرہ',
    'opportunity': 'موقع',
    'chance': 'موقع',
    'situation': 'صورتحال',
    'condition': 'حالت',
    'circumstances': 'حالات',
    'background': 'پس منظر',
    'context': 'سیاق و سباق',
    'perspective': 'نقطہ نظر',
    'view': 'نقطہ نظر',
    'opinion': 'رائے',
    'analysis': 'تجزیہ',
    'analyst': 'تجزیہ کار',
    'expert': 'ماہر',
    'specialist': 'ماہر',
    'adviser': 'مشیر',
    'advisor': 'مشیر',
    'consultant': 'مشیر',
    'negotiator': 'مذاکرات کار',
    'mediator': 'ثالث',
    'representative': 'نمائندہ',
    'delegate': 'منتخب نمائندہ',
    'envoy': 'ایلچی',
    'ambassador': 'سفیر',
    'diplomat': 'سفارت کار',
    'diplomatic': 'سفارتی',
    'embassy': 'سفارت خانہ',
    'consulate': 'قونصل خانہ',
    'delegation': 'وفد',
    'sanctions': 'پابندیاں',
    'sanction': 'پابندی',
    'embargo': 'پابندی',
    'blockade': 'ناکہ بندی',
    'siege': 'محاصرہ',
    'occupation': 'قبضہ',
    'annexation': 'الحاق',
    'independence': 'آزادی',
    'sovereignty': 'خودمختاری',
    'autonomy': 'خودمختاری',
    'freedom': 'آزادی',
    'liberty': 'آزادی',
    'democracy': 'جمہوریت',
    'democratic': 'جمہوری',
    'republic': 'جمہوریہ',
    'federation': 'وفاق',
    'union': 'اتحاد',
    'community': 'برادری',
    'society': 'معاشرہ',
    'population': 'آبادی',
    'citizen': 'شہری',
    'citizens': 'شہریوں',
    'resident': 'رہائشی',
    'family': 'خاندان',
    'families': 'خاندانوں',
    'children': 'بچے',
    'women': 'خواتین',
    'men': 'مرد',
    'youth': 'نوجوان',
    'elderly': 'بزرگ',
    'minority': 'اقلیت',
    'majority': 'اکثریت',
    'rights': 'حقوق',
    'human rights': 'انسانی حقوق',
    'equality': 'مساوات',
    'plead': 'دعوی کرنا',
    'pleads': 'دعوی کرتا ہے',
    'pleaded': 'دعوی کیا',
    'felony': 'سنگین جرم',
    'count': 'شمار',
    'counts': 'شمار',
    'indictment': 'فرد جرم',
    'indict': 'فرد جرم عائد',
    'indicted': 'فرد جرم عائد',
    'charged': 'الزام عائد',
    'charges': 'الزامات',
    'allegedly': 'الزاماً',
    'convicted': 'مجرم قرار',
    'conviction': 'سزا',
    'sentenced': 'سزا سنائی',
    'sentencing': 'سزا کا اعلان',
    'arrested': 'گرفتار',
    'detained': 'حراست میں',
    'detention': 'حراست',
    'released': 'رہا',
    'bailed': 'ضمانت پر رہا',
    'prosecute': 'استغاثہ',
    'prosecuted': 'استغاثہ دائر',
    'defend': 'دفاع',
    'defended': 'دفاع کیا',
    'appealed': 'اپیل کی',
    'dismissed': 'مسترد کیا',
    'dismissal': 'برطرفی',
    'acquit': 'بری',
    'acquitted': 'بری کیا',
    'acquittal': 'بریت',
    'testify': 'گواہی دینا',
    'testified': 'گواہی دی',
    'testimony': 'گواہی',
    'witnessed': 'گواہی دی',
    'related': 'متعلقہ',
    'relation': 'تعلق',
    'payment': 'ادائیگی',
    'pay': 'ادا کرنا',
    'paid': 'ادا کیا',
    'hush': 'خاموش',
    'illegal': 'غیر قانونی',
    'legal': 'قانونی',
    'legally': 'قانونی طور پر',
    'courtroom': 'عدالت',
    'jury': 'جری',
    'judgment': 'فیصلہ',
    'ruling': 'فیصلہ',
    'order': 'حکم',
    'ordered': 'حکم دیا',
    'ban': 'پابندی',
    'banned': 'پابندی لگا دی',
    'fine': 'جرمانہ',
    'fined': 'جرمانہ عائد',
    'penalty': 'جرمانہ',
    'punishment': 'سزا',
    'investigated': 'تحقیقات کی',
    'question': 'سوال',
    'questioned': 'پوچھ گچھ کی',
    'questioning': 'پوچھ گچھ',
    'interrogate': 'پوچھ گچھ',
    'interrogation': 'پوچھ گچھ',
    'confess': 'اعتراف',
    'confessed': 'اعتراف کیا',
    'confession': 'اعتراف جرم',
    'admit': 'تسلیم کرنا',
    'admitted': 'تسلیم کیا',
    'denial': 'انکار',
    'liability': 'ذمہ داری',
    'responsible': 'ذمہ دار',
    'accountable': 'جوابدہ',
    'oversight': 'نگرانی',
    'supervision': 'نگرانی',
    'monitor': 'نگرانی',
    'monitoring': 'نگرانی',
    'review': 'جائزہ',
    'reviewed': 'جائزہ لیا',
    'audit': 'آڈٹ',
    'scrutiny': 'جانچ پڑتال',
    'regulation': 'ضابطہ',
    'regulatory': 'ضابطہ کاری',
    'comply': 'تعمیل',
    'compliance': 'تعمیل',
    'violation': 'خلاف ورزی',
    'violate': 'خلاف ورزی',
    'violated': 'خلاف ورزی کی',
    'restriction': 'پابندی',
    'restrict': 'محدود',
    'restricted': 'محدود',
    'limit': 'حد',
    'limited': 'محدود',
    'freeze': 'منجمد',
    'frozen': 'منجمد',
    'block': 'بلاک',
    'blocked': 'بلاک کیا',
    'seize': 'ضبط',
    'seized': 'ضبط کیا',
    'confiscate': 'ضبط',
    'confiscated': 'ضبط کیا',
    'asset': 'اثاثہ',
    'assets': 'اثاثے',
    'property': 'جائیداد',
    'account': 'اکاؤنٹ',
    'accounts': 'اکاؤنٹس',
    'funds': 'فنڈز',
    'money laundering': 'منی لانڈرنگ',
    'corrupt': 'بدعنوان',
    'bribe': 'رشوت',
    'kickback': 'کمیشن',
    'embezzlement': 'خرد برد',
    'fraudulent': 'جعلی',
    'forgery': 'جعلی دستخط',
    'counterfeit': 'جعلی',
    'smuggle': 'سمگل',
    'smuggling': 'سمگلنگ',
    'trafficking': 'سمگلنگ',
    'trafficker': 'سمگلر',
    'gang': 'گروہ',
    'gangster': 'گینگسٹر',
    'mafia': 'مافیا',
    'cartel': 'کارٹل',
    'terrorist': 'دہشت گرد',
    'terrorism': 'دہشت گردی',
    'extremist': 'انتہا پسند',
    'extremism': 'انتہا پسندی',
    'militant': 'عسکریت پسند',
    'radical': 'رادیکال',
    'radicalization': 'رادیکالائزیشن',
    'insurgent': 'باغی',
    'insurgency': 'شورش',
    'rebel': 'باغی',
    'rebellion': 'بغاوت',
    'uprising': 'بغاوت',
    'revolt': 'بغاوت',
    'coup': 'بغاوت',
    'overthrow': 'معزولی',
    'oust': 'معزول',
    'ousted': 'معزول کیا',
    'depose': 'معزول',
    'deposed': 'معزول کیا',
    'exile': 'جلاوطنی',
    'exiled': 'جلاوطن',
    'asylum': 'پناہ',
    'sanctuary': 'پناہ',
    'shelter': 'پناہ',
    'protection': 'تحفظ',
    'protect': 'تحفظ',
    'protected': 'محفوظ',
    'guard': 'گارڈ',
    'guarded': 'محفوظ',
    'safe': 'محفوظ',
    'secure': 'محفوظ',
    'secured': 'محفوظ کیا',
    'peaceful': 'پرامن',
    'peacefully': 'پرامن طریقے سے',
    'truce': 'جنگ بندی',
    'armistice': 'جنگ بندی',
    'negotiate': 'مذاکرات',
    'negotiated': 'مذاکرات کیے',
    'mediate': 'ثالثی',
    'mediation': 'ثالثی',
    'arbitration': 'ثالثی',
    'settle': 'تصفیہ',
    'settlement': 'تصفیہ',
    'resolved': 'حل کیا',
    'solution': 'حل',
    'compromise': 'سمجھوتہ',
    'reconciliation': 'مفاہمت',
    'reconcile': 'مفاہمت',
    'discuss': 'بات چیت',
    'discussed': 'بات چیت کی',
    'consult': 'مشاورت',
    'coordinate': 'ہم آہنگی',
    'coordination': 'ہم آہنگی',
    'cooperation': 'تعاون',
    'cooperate': 'تعاون',
    'collaborate': 'اشتراک',
    'collaboration': 'اشتراک',
    'partnership': 'شراکت داری',
    'partner': 'شراکت دار',
    'ally': 'اتحادی',
    'allies': 'اتحادی',
    'friendly': 'دوستانہ',
    'hostile': 'مخالف',
    'enemy': 'دشمن',
    'rival': 'حریف',
    'rivalry': 'دشمنی',
    'competition': 'مقابلہ',
    'compete': 'مقابلہ',
    'competitor': 'مدمقابل',
    'contest': 'مقابلہ',
    'contender': 'امیدوار',
    'opponent': 'مخالف',
    'adversary': 'مخالف',
    'foe': 'دشمن',
    'friend': 'دوست',
    'supporter': 'حامی',
    'backer': 'حمایتی',
    'advocate': 'وکیل',
    'advocacy': 'وکالت',
    'lobby': 'لابی',
    'lobbying': 'لابی نگ',
    'endorse': 'حمایت',
    'endorsement': 'حمایت',
    'endorsed': 'حمایت کی',
    'supported': 'حمایت کی',
    'backing': 'حمایت',
    'disapprove': 'نامنظوری',
    'consent': 'رضامندی',
    'permission': 'اجازت',
    'permit': 'اجازت',
    'allowed': 'اجازت دی',
    'authorize': 'اختیار دینا',
    'authorized': 'مجاز',
    'authorization': 'اجازت',
    'certify': 'تصدیق',
    'certified': 'مصدقہ',
    'certification': 'تصدیق',
    'license': 'لائسنس',
    'licensed': 'لائسنس یافتہ',
    'registration': 'رجسٹریشن',
    'register': 'رجسٹر',
    'registered': 'رجسٹرڈ',
    'enlist': 'شمولیت',
    'enrolled': 'داخلہ لیا',
    'membership': 'رکنیت',
    'affiliate': 'وابستہ',
    'affiliated': 'وابستہ',
    'subsidiary': 'ذیلی ادارہ',
    'parent': 'والدین',
    'firm': 'فرم',
    'enterprise': 'انٹرپرائز',
    'corporation': 'کارپوریشن',
    'corporate': 'کارپوریٹ',
    'multinational': 'ملٹی نیشنل',
    'conglomerate': 'گروپ',
    'group': 'گروپ',
    'organization': 'تنظیم',
    'organize': 'منظم',
    'organized': 'منظم',
    'institution': 'ادارہ',
    'institutional': 'ادارہ جاتی',
    'foundation': 'فاؤنڈیشن',
    'trust': 'ٹرسٹ',
    'charity': 'خیراتی ادارہ',
    'charitable': 'خیراتی',
    'nonprofit': 'غیر منافع بخش',
    'welfare': 'فلاح و بہبود',
    'social': 'سماجی',
    'communal': 'فرقہ وارانہ',
    'sectarian': 'فرقہ وارانہ',
    'ethnic': 'نسلی',
    'tribal': 'قبائلی',
    'tribe': 'قبیلہ',
    'clan': 'قبیلہ',
    'race': 'نسل',
    'racial': 'نسلی',
    'religious': 'مذہبی',
    'religion': 'مذہب',
    'faith': 'عقیدہ',
    'belief': 'عقیدہ',
    'sect': 'فرقہ',
    'denomination': 'فرقہ',
    'united': 'یونائٹڈ',
    'premier': 'پریمیئر',
    'chelsea': 'چیلسی',
    'arsenal': 'آرسنل',
    'tottenham': 'ٹوٹنہم',
    'liverpool': 'لیورپول',
    'manchester': 'مانچسٹر',
    'barcelona': 'بارسلونا',
    'madrid': 'میڈرڈ',
    'juventus': 'جووینٹس',
    'bayern': 'بائرن',
    'munich': 'میونخ',
    'striker': 'سٹرائیکر',
    'manager': 'مینیجر',
    'forward': 'فارورڈ',
    'defender': 'ڈیفنڈر',
    'midfielder': 'مڈفیلڈر',
    'goalkeeper': 'گول کیپر',
    'quarter': 'کوارٹر',
    'semi': 'سیمی',
    'finals': 'فائنلز',
    'derby': 'ڈربی',
    'announced': 'اعلان کیا',
    'beats': 'شکست دیتا ہے',
    'strikes': 'حملہ کرتا ہے',
    'reserves': 'ذخائر',
    'increases': 'اضافہ ہوتا ہے',
    'falls': 'گرتا ہے',
    'falling': 'گرتا ہوا',
    'rising': 'بڑھتا ہوا',
    'highest': 'سب سے زیادہ',
    'lowest': 'سب سے کم',
    'weekly': 'ہفتہ وار',
    'monthly': 'ماہانہ',
    'yearly': 'سالانہ',
    'historic': 'تاریخی',
    'historical': 'تاریخی',
    'dramatic': 'ڈرامائی',
    'rapid': 'تیز',
    'rapidly': 'تیزی سے',
    'sudden': 'اچانک',
    'suddenly': 'اچانک',
    'immediate': 'فوری',
    'immediately': 'فوری طور پر',
    'direct': 'براہ راست',
    'directly': 'براہ راست',
    'indirect': 'بالواسطہ',
    'indirectly': 'بالواسطہ',
    'average': 'اوسط',
    'minimum': 'کم سے کم',
    'maximum': 'زیادہ سے زیادہ',
    'initial': 'ابتدائی',
    'temporary': 'عارضی',
    'permanent': 'مستقل',
    'voluntary': 'رضاکارانہ',
    'mandatory': 'لازمی',
    'compulsory': 'لازمی',
    'optional': 'اختیاری',
    'virtual': 'ورچوئل',
    'actual': 'حقیقی',
    'theoretical': 'نظریاتی',
    'practical': 'عملی',
    'technical': 'تکنیکی',
    'professional': 'پیشہ ورانہ',
    'personal': 'ذاتی',
    'physical': 'جسمانی',
    'mental': 'دماغی',
    'emotional': 'جذباتی',
    'spiritual': 'روحانی',
    'intellectual': 'دانشورانہ',
    'commercial': 'تجارتی',
    'industrial': 'صنعتی',
    'agricultural': 'زرعی',
    'municipal': 'میونسپل',
    'rural': 'دیہی',
    'urban': 'شہری',
    'amid': 'دوران',
    'reserve': 'ریزرو',
    'fall': 'گراوٹ',
    'rise': 'اضافہ',
    'unchanged': 'برقرار',
    'airstrikes': 'فضائی حملے',
    'opening': 'افتتاحی',
    'case': 'کیس',
    'saint': 'سینٹ',
    'germain': 'جرمین',
    'asia': 'ایشیا',
    'prime': 'وزیراعظم',
    'nation': 'قوم',
    'tonight': 'آج رات',
    'reach': 'پہنچ',
    'highs': 'بلند ترین',
    'lows': 'نیچ ترین',
    'transforming': 'تبدیل کر رہا ہے',
    'transformed': 'تبدیل ہوگیا',
    'healthcare': 'صحت کی دیکھ بھال',
    'adds': 'شامل کرتا ہے',
    'added': 'شامل کیا',
    'comes': 'آتا ہے',
    'takes': 'لیتا ہے',
    'calls': 'بلاتا ہے',
    'plays': 'کھیلتا ہے',
    'shows': 'دکھاتا ہے',
    'makes': 'بناتا ہے',
    'moves': 'منتقل',
    'based': 'کی بنیاد پر',
    'named': 'نامزد',
    'called': 'کہلاتا ہے',
    'known': 'معروف',
    'expected': 'متوقع',
    'believed': 'خیال کیا جاتا ہے',
    'considered': 'سمجھا جاتا ہے',
    'regarded': 'سمجھا جاتا ہے',
    'including': 'بشمول',
    'following': 'بعد میں',
    'heading': 'سرخی',
    'looking': 'دیکھ رہا ہے',
    'leading': 'معروف',
    'working': 'کام کر رہا ہے',
    'meeting': 'میٹنگ',
    'meetings': 'اجلاس',
    'discussions': 'بات چیت',
    'operations': 'آپریشنز',
    'investigations': 'تحقیقات',
    'negotiations': 'مذاکرات',
    'relations': 'تعلقات',
    'countries': 'ممالک',
    'cities': 'شہر',
    'officers': 'افسران',
    'members': 'ارکان',
    'players': 'کھلاڑیوں',
    'supporters': 'حامیوں',
    'residents': 'رہائشیوں',
    'officials': 'سرکاری ذرائع',
    'statements': 'بیانات',
    'agreements': 'معاہدے',
    'projects': 'منصوبے',
    'programs': 'پروگرام',
    'services': 'خدمات',
    'systems': 'نظام',
    'forces': 'افواج',
    'attacks': 'حملے',
    'raids': 'چھاپے',
    'changes': 'تبدیلیاں',
    'issues': 'مسائل',
    'problems': 'مسائل',
    'matters': 'معاملات',
    'concerns': 'خدشات',
    'efforts': 'کوششیں',
    'measures': 'اقدامات',
    'steps': 'اقدامات',
    'reforms': 'اصلاحات',
    'results': 'نتائج',
    'impacts': 'اثرات',
    'effects': 'اثرات',
    'benefits': 'فوائد',
    'challenges': 'چیلنجز',
    'opportunities': 'مواقع',
    'threats': 'خطرات',
    'risks': 'خطرات',
    'causes': 'وجوہات',
    'factors': 'عوامل',
  };
  for (const [en, ur] of Object.entries(manual)) {
    ENGLISH_TO_URDU[en] = ur;
  }
}

buildReverseMap();

// Extended vocabulary: proper Urdu translations for common news words
// Added after buildReverseMap() to avoid duplicate-key issues in object literals
const EXTENDED: Record<string, string> = {
  // Numbers (critical missing ones)
  'zero': 'صفر', 'one': 'ایک', 'two': 'دو', 'three': 'تین', 'four': 'چار',
  'five': 'پانچ', 'six': 'چھ', 'seven': 'سات', 'eight': 'آٹھ', 'nine': 'نو',
  'ten': 'دس', 'eleven': 'گیارہ', 'twelve': 'بارہ', 'dozen': 'درجن',
  'dozens': 'درجنوں',
  // Critical missing verbs from test headlines
  'visit': 'دورہ', 'visits': 'دورہ', 'visited': 'دورہ کیا',
  'drop': 'کمی', 'dropped': 'گر گیا',
  'face': 'سامنا', 'faces': 'سامنا', 'faced': 'سامنا کرنا پڑا',
  'gather': 'جمع', 'gathered': 'جمع ہوئے', 'gathering': 'اجتماع',
  'surge': 'اضافہ', 'surges': 'اضافہ', 'surged': 'اضافہ ہوا',
  'discover': 'دریافت', 'discovers': 'دریافت',
  'unveil': 'پیش', 'unveils': 'پیش',
  'soar': 'اضافہ', 'soars': 'اضافہ', 'soared': 'اضافہ ہوا',
  'sweep': 'پھیلنا', 'sweeps': 'پھیلنا', 'swept': 'پھیل گیا',
  'rule': 'فیصلہ', 'rules': 'فیصلہ', 'ruled': 'فیصلہ دیا',
  'resolve': 'حل', 'resolves': 'حل', 'resolved': 'حل ہوا',
  'bowled': 'آؤٹ', 'bat': 'بلے بازی',
  'level': 'سطح', 'levels': 'سطحیں',
  'scientist': 'سائنسدان', 'scientists': 'سائنسدانوں',
  'uncertainty': 'غیر یقینی',
  'wildfire': 'جنگل کی آگ', 'wildfires': 'جنگل کی آگ',
  'batsman': 'بلے باز',
  'title': 'اعزاز',
  'heavy': 'شدید',
  'child': 'بچہ', 'children': 'بچے',
  'ring': 'گروہ',
  'crackdown': 'کریک ڈاؤن',
  'pacific': 'بحرالکاہل',
  'california': 'کیلیفورنیا',
  'sharif': 'شریف',
  'shehbaz': 'شہباز',
  'bowler': 'گیند باز',
  'kickoff': 'کک آف',
  'barnaby': 'بارنبی',
  'joice': 'جوائس',
  // Common weather
  'forecast': 'پیشن گوئی', 'humidity': 'نمی',
  'rainfall': 'بارش', 'sunshine': 'دھوپ',
  'cloudy': 'ابر آلود', 'fog': 'دھند', 'mist': 'دھند',
  'haze': 'دھند', 'thunder': 'گرج', 'lightning': 'بجلی',
  'hail': 'اولے', 'monsoon': 'مون سون',
  'gale': 'آندھی', 'blizzard': 'برفانی طوفان',
  'chilly': 'سرد', 'moderate': 'معتدل',
  'torrential': 'موسلا دھار', 'drought': 'خشک سالی',
  'sunny': 'دھوپ',
  // Sports
  'wicket': 'وکٹ', 'innings': 'اننگز', 'over': 'اوور',
  'century': 'سنچری', 'umpire': 'امپائر', 'referee': 'ریفری',
  'pitch': 'پچ', 'squad': 'اسکواڈ',
  'fixture': 'میچ', 'penalty': 'پینلٹی', 'foul': 'فاؤل',
  'corner': 'کارنر', 'header': 'ہیڈر',
  'possession': 'قبضہ', 'substitute': 'متبادل',
  'offside': 'آف سائیڈ', 'tackle': 'ٹیکل',
  // Economy
  'indicator': 'اشاریہ', 'outlook': 'نقطہ نظر',
  'trend': 'رجحان', 'downturn': 'مندی',
  'expansion': 'توسیع', 'contraction': 'سکڑاؤ',
  'recession': 'کساد بازاری', 'recovery': 'بحالی',
  'boom': 'عروج', 'crash': 'کریش',
  'rally': 'تیزی', 'dividend': 'منافع', 'yield': 'پیداوار',
  'bond': 'بانڈ', 'bonds': 'بانڈز',
  'liquidity': 'لیکویڈیٹی', 'bankruptcy': 'دیوالیہ پن',
  'foreclosure': 'ضبطی', 'collateral': 'ضمانت',
  'mortgage': 'رہن',
  // Military
  'battalion': 'بٹالین', 'brigade': 'بریگیڈ',
  'regiment': 'رجمنٹ', 'corps': 'کور',
  'garrison': 'چھاؤنی', 'convoy': 'قافلہ',
  'reconnaissance': 'جاسوسی', 'artillery': 'توپ خانہ',
  'infantry': 'پیادہ فوج', 'submarine': 'آبدوز',
  'aircraft': 'طیارہ', 'helicopter': 'ہیلی کاپٹر',
  'bomber': 'بمبار', 'ammunition': 'گولہ بارود',
  'sniper': 'نشانہ باز', 'guerrilla': 'گوریلا',
  // Crime/Legal
  'abduction': 'اغوا', 'hijack': 'اغوا',
  'robbery': 'ڈاکہ', 'burglary': 'چوری',
  'arson': 'آتش زنی', 'homicide': 'قتل',
  'harassment': 'ہراسانی', 'eviction': 'بے دخلی',
  'extradition': 'حوالگی', 'deportation': 'ملک بدری',
  'forgery': 'جعلسازی', 'perjury': 'جھوٹی گواہی',
  'contempt': 'توہین', 'injunction': 'حکم امتناعی',
  'summons': 'طلبی', 'warrant': 'وارنٹ',
  // Health
  'epidemic': 'وبا', 'endemic': 'مقامی وبا',
  'inflammation': 'سوزش', 'fracture': 'فریکچر',
  'sprain': 'موچ', 'allergy': 'الرجی', 'asthma': 'دمہ',
  'tuberculosis': 'تپ دق', 'malaria': 'ملیریا',
  'cholera': 'ہیضہ', 'typhoid': 'ٹائیفائیڈ',
  'hepatitis': 'ہیپاٹائٹس', 'pneumonia': 'نمونیا',
  'stroke': 'فالج', 'paralysis': 'فالج',
  'seizure': 'دورہ', 'coma': 'کوما',
  'transplant': 'پیوند کاری', 'donor': 'عطیہ کنندہ',
  'tissue': 'بافت', 'cell': 'خلیہ',
  'gene': 'جین', 'dna': 'ڈی این اے',
  // Common verbs in present/past forms
  'reduce': 'کم', 'reduces': 'کم', 'reduced': 'کم ہوا',
  'increase': 'بڑھانا', 'increases': 'بڑھتا ہے', 'increased': 'بڑھ گیا',
  'expand': 'پھیلانا', 'expands': 'پھیلتا ہے', 'expanded': 'پھیل گیا',
  'extend': 'بڑھانا', 'extends': 'بڑھاتا ہے', 'extended': 'بڑھا دیا',
  'grow': 'بڑھنا', 'grows': 'بڑھتا ہے', 'grew': 'بڑھ گیا',
  'shrink': 'سکڑنا', 'shrinks': 'سکڑتا ہے', 'shrank': 'سکڑ گیا',
  'arrive': 'پہنچنا', 'arrives': 'پہنچتا ہے', 'arrived': 'پہنچ گیا',
  'depart': 'روانہ', 'departs': 'روانہ', 'departed': 'روانہ ہوا',
  'enter': 'داخل', 'enters': 'داخل', 'entered': 'داخل ہوا',
  'exit': 'باہر', 'exits': 'باہر', 'exited': 'باہر نکلا',
  'remove': 'ہٹانا', 'removes': 'ہٹاتا ہے', 'removed': 'ہٹا دیا',
  'replace': 'تبدیل', 'replaces': 'بدلتا ہے', 'replaced': 'بدل دیا',
  'save': 'بچانا', 'saves': 'بچاتا ہے', 'saved': 'بچا لیا',
  'spend': 'خرچ', 'spends': 'خرچ کرتا ہے', 'spent': 'خرچ کیا',
  'borrow': 'ادھار لینا', 'borrows': 'ادھار لیتا ہے', 'borrowed': 'ادھار لیا',
  'lend': 'قرض دینا', 'lends': 'قرض دیتا ہے', 'lent': 'قرض دیا',
  'purchase': 'خرید', 'purchases': 'خرید', 'purchased': 'خریدا',
  'deliver': 'پہنچانا', 'delivers': 'پہنچاتا ہے', 'delivered': 'پہنچا دیا',
  'receive': 'وصول', 'receives': 'وصول کرتا ہے', 'received': 'وصول کیا',
  'send': 'بھیجنا', 'sends': 'بھیجتا ہے', 'sent': 'بھیج دیا',
  'carry': 'لے جانا', 'carries': 'لے جاتا ہے', 'carried': 'لے گیا',
  'bring': 'لانا', 'brings': 'لاتا ہے', 'brought': 'لایا',
  'seek': 'تلاش', 'seeks': 'تلاش کرتا ہے', 'sought': 'تلاش کیا',
  'search': 'تلاش', 'searches': 'تلاش کرتا ہے',
  'find': 'تلاش', 'finds': 'پاتا ہے', 'found': 'پایا',
  'create': 'تخلیق', 'creates': 'تخلیق کرتا ہے', 'created': 'تخلیق کیا',
  'destroy': 'تباہ', 'destroys': 'تباہ کرتا ہے',
  'fight': 'لڑنا', 'fights': 'لڑتا ہے', 'fought': 'لڑا',
  'struggle': 'جدوجہد', 'struggles': 'جدوجہد',
  'succeed': 'کامیاب', 'succeeds': 'کامیاب ہوتا ہے', 'succeeded': 'کامیاب ہوا',
  'fail': 'ناکام', 'fails': 'ناکام ہوتا ہے', 'failed': 'ناکام ہوا',
  'forbid': 'منع', 'forbids': 'منع کرتا ہے', 'forbidden': 'منع',
  'legalize': 'قانونی', 'legalizes': 'قانونی',
  'cancel': 'منسوخ', 'cancels': 'منسوخ کرتا ہے', 'cancelled': 'منسوخ کر دیا',
  'postpone': 'مؤخر', 'postpones': 'مؤخر کرتا ہے', 'postponed': 'مؤخر کر دیا',
  'schedule': 'شیڈول', 'schedules': 'شیڈول',
  'oppose': 'مخالفت', 'opposes': 'مخالفت کرتا ہے', 'opposed': 'مخالفت کی',
  'resist': 'مزاحمت', 'resists': 'مزاحمت کرتا ہے',
  'ignore': 'نظر انداز', 'ignores': 'نظر انداز',
  'contain': 'شامل', 'contains': 'شامل ہے',
  'involve': 'شامل', 'involves': 'شامل ہے',
  'require': 'ضرورت', 'requires': 'ضرورت ہے',
  'choose': 'انتخاب', 'chooses': 'انتخاب کرتا ہے', 'chose': 'انتخاب کیا',
  'decide': 'فیصلہ', 'decides': 'فیصلہ کرتا ہے', 'decided': 'فیصلہ کیا',
  'determine': 'تعین', 'determines': 'تعین کرتا ہے', 'determined': 'تعین کیا',
  'solve': 'حل', 'solves': 'حل کرتا ہے',
  'correct': 'درست', 'corrects': 'درست کرتا ہے',
  'fix': 'ٹھیک', 'fixes': 'ٹھیک کرتا ہے', 'fixed': 'ٹھیک کیا',
  'repair': 'مرمت', 'repairs': 'مرمت',
  'preserve': 'محفوظ', 'preserves': 'محفوظ کرتا ہے',
  'destroyed': 'تباہ کیا',
  'educate': 'تعلیم', 'educates': 'تعلیم',
  'inform': 'مطلع', 'informs': 'مطلع کرتا ہے',
  'notify': 'مطلع', 'notifies': 'مطلع کرتا ہے',
  'remind': 'یاد دہانی', 'reminds': 'یاد دلاتا ہے', 'reminded': 'یاد دلایا',
  'forget': 'بھولنا', 'forgets': 'بھولتا ہے', 'forgot': 'بھول گیا',
  'recognize': 'پہچاننا', 'recognizes': 'پہچانتا ہے',
  'identify': 'شناخت', 'identifies': 'شناخت کرتا ہے', 'identified': 'شناخت کیا',
  'describe': 'بیان', 'describes': 'بیان کرتا ہے',
  'explain': 'وضاحت', 'explains': 'وضاحت کرتا ہے', 'explained': 'وضاحت کی',
  'clarify': 'واضح', 'clarifies': 'واضح کرتا ہے',
  'define': 'تعریف', 'defines': 'تعریف کرتا ہے',
  'illustrate': 'وضاحت', 'illustrates': 'وضاحت',
  'interpret': 'تشریح', 'interprets': 'تشریح کرتا ہے',
  'express': 'اظہار', 'expresses': 'اظہار کرتا ہے',
  'communicate': 'بات چیت', 'communicates': 'بات چیت',
  'indicate': 'اشارہ', 'indicates': 'اشارہ کرتا ہے', 'indicated': 'اشارہ کیا',
  'imply': 'اشارہ', 'implies': 'اشارہ', 'implied': 'اشارہ کیا',
  'symbolize': 'علامت', 'symbolizes': 'علامت',
  'stay': 'رہنا', 'stays': 'رہتا ہے', 'stayed': 'رہا',
  'wait': 'انتظار', 'waits': 'انتظار کرتا ہے', 'waited': 'انتظار کیا',
  'proceed': 'آگے بڑھنا', 'proceeds': 'آگے بڑھتا ہے', 'proceeded': 'آگے بڑھا',
  'enhance': 'بہتر', 'enhances': 'بہتر',
  'weaken': 'کمزور', 'weakens': 'کمزور کرتا ہے', 'weakened': 'کمزور ہوا',
  'damage': 'نقصان', 'damages': 'نقصان',
  'harm': 'نقصان', 'harms': 'نقصان',
  'hurt': 'چوٹ', 'hurts': 'چوٹ',
  'poison': 'زہر', 'poisons': 'زہر',
  'contaminate': 'آلودہ', 'contaminates': 'آلودہ',
  'pollute': 'آلودہ', 'pollutes': 'آلودہ',
  'separate': 'علیحدہ', 'separates': 'علیحدہ',
  'divide': 'تقسیم', 'divides': 'تقسیم کرتا ہے',
  'connect': 'جوڑنا', 'connects': 'جوڑتا ہے', 'connected': 'منسلک',
  'heat': 'گرم', 'heats': 'گرم',
  'cool': 'ٹھنڈا', 'cools': 'ٹھنڈا',
  'melt': 'پگھلنا', 'melts': 'پگھلتا ہے', 'melted': 'پگھل گیا',
  'burn': 'جلنا', 'burns': 'جلتا ہے', 'burnt': 'جل گیا',
  'survive': 'بچنا', 'survives': 'بچ جاتا ہے', 'survived': 'بچ گیا',
  'escape': 'فرار', 'escapes': 'فرار', 'escaped': 'فرار ہوگیا',
  'flee': 'فرار', 'flees': 'فرار', 'fled': 'فرار ہوگیا',
  'chase': 'پیچھا', 'chases': 'پیچھا کرتا ہے',
  'track': 'ٹریک', 'tracks': 'ٹریک',
  'monitor': 'نگرانی', 'monitors': 'نگرانی',
  'observe': 'مشاہدہ', 'observes': 'مشاہدہ کرتا ہے',
  'listen': 'سننا', 'listens': 'سنتی ہے',
  'feel': 'محسوس', 'feels': 'محسوس کرتا ہے', 'felt': 'محسوس کیا',
  'think': 'سوچنا', 'thinks': 'سوچتا ہے', 'thought': 'سوچا',
  'trust': 'بھروسہ', 'trusts': 'بھروسہ کرتا ہے',
  'doubt': 'شک', 'doubts': 'شک',
  'suppose': 'فرض', 'supposes': 'فرض کرتا ہے',
  'assume': 'فرض', 'assumes': 'فرض کرتا ہے',
  'consider': 'غور', 'considers': 'غور کرتا ہے',
  'reflect': 'عکاسی', 'reflects': 'عکاسی کرتا ہے',
  'imagine': 'تصور', 'imagines': 'تصور کرتا ہے',
  'comprehend': 'سمجھنا', 'comprehends': 'سمجھتا ہے',
  'realize': 'احساس', 'realizes': 'احساس ہوتا ہے',
  'proclaim': 'اعلان', 'proclaims': 'اعلان',
  'affirm': 'تصدیق', 'affirms': 'تصدیق',
  'verify': 'تصدیق', 'verifies': 'تصدیق',
  'disagree': 'اختلاف', 'disagrees': 'اختلاف',
  'disapprove': 'نامنظور', 'disapproves': 'نامنظور',
  'punish': 'سزا', 'punishes': 'سزا دیتا ہے', 'punished': 'سزا دی',
  'reward': 'انعام', 'rewards': 'انعام',
  'apologize': 'معافی', 'apologizes': 'معافی مانگتا ہے', 'apologized': 'معافی مانگی',
  'forgive': 'معاف', 'forgives': 'معاف کرتا ہے', 'forgave': 'معاف کیا',
  'pardon': 'معاف', 'pardons': 'معاف',
  'bless': 'برکت', 'blesses': 'برکت',
  'curse': 'لعنت', 'curses': 'لعنت',
  'condemn': 'مذمت', 'condemns': 'مذمت کرتا ہے',
  'indict': 'فرد جرم', 'indicts': 'فرد جرم', 'indicted': 'فرد جرم عائد',
  'prosecute': 'استغاثہ', 'prosecutes': 'استغاثہ',
  'sue': 'مقدمہ', 'sues': 'مقدمہ',
  'settle': 'تصفیہ', 'settles': 'تصفیہ',
  'mediate': 'ثالثی', 'mediates': 'ثالثی',
  'arbitrate': 'ثالثی', 'arbitrates': 'ثالثی',
  'reconcile': 'مفاہمت', 'reconciles': 'مفاہمت',
  'compromise': 'سمجھوتہ', 'compromises': 'سمجھوتہ',
  'surrender': 'ہتھیار ڈال', 'surrenders': 'ہتھیار ڈالتا ہے', 'surrendered': 'ہتھیار ڈال دیا',
  'kill': 'ہلاک', 'killed': 'ہلاک',
  'unresolved': 'حل طلب',
  'pm': 'وزیراعظم',
  'sell-off': 'فروخت کا دباؤ', 'selloff': 'فروخت کا دباؤ',
  'submit': 'پیش', 'submits': 'پیش کرتا ہے',
  'obey': 'ماننا', 'obeys': 'مانتا ہے',
  'honor': 'عزت', 'honors': 'عزت',
  'appreciate': 'تعریف', 'appreciates': 'تعریف',
  'admire': 'تعریف', 'admires': 'تعریف',
  'prefer': 'ترجیح', 'prefers': 'ترجیح دیتا ہے', 'preferred': 'ترجیح دی',
  'pick': 'چننا', 'picks': 'چنتا ہے', 'picked': 'چنا',
  'collect': 'جمع', 'collects': 'جمع کرتا ہے',
  'distribute': 'تقسیم', 'distributes': 'تقسیم کرتا ہے',
  'share': 'بانٹنا', 'shares': 'بانٹتا ہے',
  'obtain': 'حاصل', 'obtains': 'حاصل کرتا ہے',
  'acquire': 'حاصل', 'acquires': 'حاصل کرتا ہے',
  'gain': 'حاصل', 'gains': 'حاصل کرتا ہے',
  'lose': 'کھونا', 'loses': 'کھوتا ہے',
  'catch': 'پکڑنا', 'catches': 'پکڑتا ہے', 'caught': 'پکڑا',
  'trap': 'پھنسنا', 'traps': 'پھنساتا ہے', 'trapped': 'پھنس گیا',
  'cheat': 'دھوکہ', 'cheats': 'دھوکہ دیتا ہے',
  'deceive': 'دھوکہ', 'deceives': 'دھوکہ',
  'copy': 'نقل', 'copies': 'نقل کرتا ہے',
  // Common nouns & concepts
  'situation': 'صورتحال', 'condition': 'حالت',
  'circumstance': 'حالت', 'circumstances': 'حالات',
  'background': 'پس منظر', 'context': 'سیاق و سباق',
  'perspective': 'نقطہ نظر', 'view': 'نقطہ نظر',
  'analysis': 'تجزیہ', 'analyst': 'تجزیہ کار',
  'envoy': 'ایلچی', 'ambassador': 'سفیر',
  'diplomat': 'سفارت کار', 'diplomatic': 'سفارتی',
  'embassy': 'سفارت خانہ', 'consulate': 'قونصل خانہ',
  'delegation': 'وفد',
  'embargo': 'پابندی', 'blockade': 'ناکہ بندی',
  'siege': 'محاصرہ', 'occupation': 'قبضہ',
  'independence': 'آزادی', 'sovereignty': 'خودمختاری',
  'autonomy': 'خودمختاری', 'freedom': 'آزادی', 'liberty': 'آزادی',
  'democracy': 'جمہوریت', 'democratic': 'جمہوری',
  'republic': 'جمہوریہ', 'federation': 'وفاق',
  'union': 'اتحاد', 'community': 'برادری',
  'population': 'آبادی',
  'equality': 'مساوات', 'rights': 'حقوق',
  'minority': 'اقلیت', 'majority': 'اکثریت',
  // Quantity & frequency
  'several': 'کئی', 'numerous': 'متعدد', 'countless': 'بے شمار',
  'plenty': 'کافی', 'sufficient': 'کافی',
  'insufficient': 'ناکافی', 'adequate': 'مناسب',
  'additional': 'اضافی', 'excess': 'اضافی',
  'spare': 'فالتو', 'entire': 'پورا',
  'partial': 'جزوی', 'half': 'آدھا', 'quarter': 'چوتھائی',
  'single': 'واحد', 'double': 'دگنا', 'triple': 'تگنا',
  'daily': 'روزانہ', 'quarterly': 'سہ ماہی',
  // Descriptions
  'beautiful': 'خوبصورت', 'ugly': 'بدصورت',
  'rich': 'امیر', 'wealthy': 'امیر',
  'poor': 'غریب',
  'fast': 'تیز', 'slow': 'سست',
  'difficult': 'مشکل',
  'simple': 'سادہ', 'complex': 'پیچیدہ', 'complicated': 'پیچیدہ',
  'cheap': 'سستا', 'expensive': 'مہنگا', 'costly': 'مہنگا',
  'popular': 'مقبول', 'unpopular': 'غیر مقبول',
  'common': 'عام', 'uncommon': 'غیر معمولی',
  'rare': 'نایاب', 'unique': 'منفرد',
  'extraordinary': 'غیر معمولی',
  'abnormal': 'غیر معمولی', 'regular': 'باقاعدہ',
  'irregular': 'غیر باقاعدہ',
  'proper': 'مناسب', 'improper': 'نامناسب',
  'incorrect': 'غلط', 'accurate': 'درست', 'inaccurate': 'غلط',
  'genuine': 'حقیقی', 'authentic': 'مستند',
  'perfect': 'کامل', 'flawless': 'بے عیب',
  'broken': 'ٹوٹا ہوا',
  // Useful concepts
  'usage': 'استعمال', 'useful': 'کارآمد',
  'useless': 'بیکار', 'helpful': 'مددگار',
  'harmful': 'نقصان دہ', 'dangerous': 'خطرناک',
  'unsafe': 'غیر محفوظ',
  'impossible': 'ناممکن',
  'improbable': 'غیر متوقع', 'unlikely': 'غیر متوقع',
  'maybe': 'شاید', 'perhaps': 'شاید',
  'rarely': 'شاذ و نادر',
  'frequently': 'بار بار', 'occasionally': 'کبھی کبھار',
  'eventually': 'بالآخر', 'ultimately': 'بالآخر',
  'originally': 'اصل میں',
  'meanwhile': 'اس دوران', 'furthermore': 'مزید برآں',
  'moreover': 'مزید', 'nevertheless': 'بہر حال',
  'however': 'تاہم', 'therefore': 'لہذا',
  'otherwise': 'ورنہ', 'instead': 'بجائے',
  // People
  'person': 'شخص', 'persons': 'افراد',
  'neighbor': 'پڑوسی', 'neighbors': 'پڑوسیوں',
  'guest': 'مہمان',
  'owner': 'مالک', 'tenant': 'کرایہ دار',
  'boss': 'باس', 'employee': 'ملازم',
  'employer': 'آجر', 'colleague': 'ساتھی',
  'prisoner': 'قیدی', 'prisoners': 'قیدیوں',
  'hostage': 'یرغمال', 'hostages': 'یرغمالی',
  'orphan': 'یتیم', 'widow': 'بیوہ', 'widower': 'بیوہ',
  // Geography
  'ocean': 'سمندر', 'sea': 'سمندر',
  'mountain': 'پہاڑ', 'mountains': 'پہاڑوں',
  'hill': 'پہاڑی', 'hills': 'پہاڑیوں',
  'valley': 'وادی', 'desert': 'صحرا',
  'jungle': 'جنگل',
  'lake': 'جھیل', 'island': 'جزیرہ',
  'peninsula': 'جزیرہ نما', 'continent': 'براعظم',
  'village': 'گاؤں', 'villages': 'گاؤں',
  'neighborhood': 'محلہ',
  // Transportation
  'transportation': 'ٹرانسپورٹ',
  'vehicle': 'گاڑی', 'vehicles': 'گاڑیوں',
  'bus': 'بس', 'buses': 'بسیں',
  'plane': 'جہاز', 'planes': 'جہاز',
  'ship': 'جہاز', 'ships': 'جہاز',
  'truck': 'ٹرک', 'trucks': 'ٹرک',
  'taxi': 'ٹیکسی', 'bicycle': 'سائیکل',
  'motorcycle': 'موٹر سائیکل',
  'pedestrian': 'پیدل', 'passenger': 'مسافر',
  'driver': 'ڈرائیور', 'pilot': 'پائلٹ',
  'crew': 'عملہ',
  // Communication
  'fax': 'فیکس', 'telephone': 'ٹیلی فون',
  'signal': 'سگنل',
  'comment': 'تبصرہ', 'comments': 'تبصرے',
  'feedback': 'رائے',
  // Time
  'moment': 'لمحہ', 'moments': 'لمحات',
  'duration': 'دورانیہ', 'interval': 'وقفہ',
  'holiday': 'چھٹی', 'holidays': 'چھٹیاں',
  'vacation': 'چھٹی', 'leave': 'چھٹی',
  'birthday': 'سالگرہ', 'anniversary': 'سالگرہ',
  'deadline': 'آخری تاریخ',
  // Movement
  'move': 'حرکت', 'moved': 'منتقل ہوگیا',
  'walk': 'چلنا', 'walks': 'چلتا ہے', 'walked': 'چلا',
  'run': 'دوڑنا', 'runs': 'دوڑتا ہے', 'ran': 'دوڑا',
  'drive': 'چلانا', 'drives': 'چلاتا ہے', 'drove': 'چلایا',
  'fly': 'اڑنا', 'flies': 'اڑتا ہے', 'flew': 'اڑا',
  'swim': 'تیرنا', 'swims': 'تیرتا ہے', 'swam': 'تیرا',
  'climb': 'چڑھنا', 'climbs': 'چڑھتا ہے', 'climbed': 'چڑھ گیا',
  'crawl': 'رینگنا', 'crawls': 'رینگتا ہے',
  'jump': 'چھلانگ', 'jumps': 'چھلانگ', 'jumped': 'چھلانگ لگا',
  'slip': 'پھسلنا', 'slips': 'پھسلتا ہے', 'slipped': 'پھسل گیا',
  'lift': 'اٹھانا', 'lifts': 'اٹھاتا ہے', 'lifted': 'اٹھایا',
  'lower': 'نیچا', 'lowers': 'نیچا کرتا ہے', 'lowered': 'نیچا کیا',
  'raise': 'بلند', 'raises': 'بلند کرتا ہے', 'raised': 'بلند کیا',
  'push': 'دھکیلنا', 'pushes': 'دھکیلتا ہے', 'pushed': 'دھکیلا',
  'pull': 'کھینچنا', 'pulls': 'کھینچتا ہے', 'pulled': 'کھینچا',
  'throw': 'پھینکنا', 'throws': 'پھینکتا ہے', 'threw': 'پھینکا',
  'turn': 'موڑنا', 'turns': 'موڑتا ہے', 'turned': 'موڑ دیا',
  'bend': 'موڑنا', 'bends': 'موڑتا ہے', 'bent': 'موڑ دیا',
  'tear': 'پھاڑنا', 'tears': 'پھاڑتا ہے', 'tore': 'پھاڑ دیا',
  'cut': 'کاٹنا', 'cuts': 'کاٹتا ہے',
  'dig': 'کھودنا', 'digs': 'کھودتا ہے', 'dug': 'کھود دیا',
  'press': 'دبانا', 'presses': 'دباتا ہے', 'pressed': 'دبایا',
  'squeeze': 'نچوڑنا', 'squeezes': 'نچوڑتا ہے',
  'stretch': 'کھینچنا', 'stretches': 'کھینچتا ہے',
  'cover': 'ڈھانپنا', 'covers': 'ڈھانپتا ہے', 'covered': 'ڈھانپ لیا',
  'wrap': 'لپیٹنا', 'wraps': 'لپیٹتا ہے', 'wrapped': 'لپیٹا',
  'uncover': 'کھولنا', 'uncovers': 'کھولتا ہے',
  // Social
  'marry': 'شادی', 'marries': 'شادی کرتا ہے', 'married': 'شادی شدہ',
  'divorce': 'طلاق', 'divorces': 'طلاق', 'divorced': 'طلاق یافتہ',
  'donate': 'عطیہ', 'donates': 'عطیہ کرتا ہے',
  'celebrate': 'جشن', 'celebrates': 'جشن مناتا ہے', 'celebrated': 'جشن منایا',
  'mourn': 'غم', 'mourns': 'غم کرتا ہے',
  'grieve': 'غم', 'grieves': 'غم کرتا ہے',
  'congratulate': 'مبارکباد', 'congratulated': 'مبارکباد دی',
  'invite': 'دعوت', 'invites': 'دعوت دیتا ہے', 'invited': 'دعوت دی',
  'host': 'میزبانی', 'hosts': 'میزبانی', 'hosted': 'میزبانی کی',
  'attend': 'شرکت', 'attends': 'شرکت کرتا ہے', 'attended': 'شرکت کی',
  'participate': 'حصہ', 'participates': 'حصہ لیتا ہے',
  'resign': 'استعفی', 'resigns': 'استعفی دیتا ہے',
  'retire': 'ریٹائر', 'retires': 'ریٹائر',
  'fire': 'برطرف', 'fires': 'برطرف',
  'hire': 'بھرتی', 'hires': 'بھرتی کرتا ہے',
  'promote': 'ترقی دیتا ہے', 'promotes': 'ترقی دیتا ہے',
  'demote': 'تنزلی', 'demotes': 'تنزلی',
  // Commerce
  'rent': 'کرایہ', 'rents': 'کرایہ',
  'lease': 'لیز', 'leases': 'لیز',
  'fee': 'فیس', 'fees': 'فیسیں',
  'refund': 'واپسی', 'refunds': 'واپسی',
  'discount': 'رعایت', 'discounts': 'رعایت',
  'tip': 'ٹپ', 'tips': 'ٹپ',
  'receipt': 'رسید', 'invoice': 'انوائس',
  'cash': 'نقد', 'credit': 'کریڈٹ',
  'debit': 'ڈیبٹ', 'balance': 'بیلنس',
  // ── Frequently missing words from RSS headlines ──
  'years': 'سال', 'tells': 'بتاتا ہے', 'prices': 'قیمتیں',
  'labour': 'لیبر', 'wins': 'جیت', 'offensive': 'جارحانہ',
  'terms': 'شرائط', 'sees': 'دیکھتا ہے', 'work': 'کام',
  'most': 'زیادہ تر', 'jobs': 'نوکریاں', 'them': 'انہیں',
  'former': 'سابق', 'fear': 'خوف', 'sky': 'آسمان',
  'hundreds': 'سینکڑوں', 'suspected': 'مشتبہ', 'staff': 'عملہ',
  'star': 'سٹار', 'house': 'گھر', 'middle': 'وسط',
  'east': 'مشرق', 'north': 'شمال', 'south': 'جنوب',
  'good': 'اچھا', 'age': 'عمر', 'generation': 'نسل',
  'england': 'انگلینڈ', 'deadly': 'مہلک', 'huge': 'بہت بڑا',
  'nearly': 'تقریبا', 'access': 'رسائی', 'experts': 'ماہرین',
  'study': 'مطالعہ', 'costs': 'اخراجات', 'secret': 'خفیہ',
  'workers': 'کارکنان', 'big': 'بڑا', 'hard': 'مشکل',
  'parents': 'والدین', 'solar': 'شمسی', 'flight': 'پرواز',
  'sets': 'سیٹ', 'line': 'لائن', 'hit': 'مارا',
  'open': 'کھلا', 'chip': 'چپ', 'car': 'گاڑی',
  'goes': 'جاتا ہے', 'reveals': 'انکشاف', 'bid': 'بولی',
  'silence': 'خاموشی', 'images': 'تصاویر', 'scale': 'پیمانہ',
  'use': 'استعمال', 'get': 'حاصل', 'waste': 'فضول',
  'sit': 'بیٹھنا', 'association': 'ایسوسی ایشن',
  'classic': 'کلاسک', 'grand': 'عظیم', 'guide': 'گائیڈ',
  'hits': 'مارتا ہے', 'getting': 'مل رہا', 'expose': 'بے نقاب',
  'suggests': 'ظاہر کرتا ہے', 'hikes': 'اضافہ',
  'watchdog': 'نگران',
  'campus': 'کیمپس', 'tour': 'دورہ',
  'producers': 'پروڈیوسرز', 'controversial': 'متنازعہ',
  'bans': 'پابندیاں', 'greater': 'زیادہ', 'rocked': 'ہل گیا',
  'rollout': 'اجراء', 'using': 'استعمال کرتے ہوئے',
};
for (const [en, ur] of Object.entries(EXTENDED)) {
  ENGLISH_TO_URDU[en] = ur;
}

function transliterateWord(word: string): string {
  return word;
}

function stemWord(word: string): string | null {
  const attempts: string[] = [];
  const w = word;
  if (w.endsWith('ies') && w.length > 4) attempts.push(w.slice(0, -3) + 'y');
  if (w.endsWith('ves') && w.length > 4) attempts.push(w.slice(0, -3) + 'f');
  if (/(?:sh|ch|ss|o|x)es$/.test(w) && w.length > 4) attempts.push(w.slice(0, -2));
  if (w.endsWith('s') && !w.endsWith('ss') && w.length > 3) attempts.push(w.slice(0, -1));
  if (w.endsWith('ing') && w.length > 4) {
    const s = w.slice(0, -3);
    attempts.push(s);
    if (s.length > 2 && s.at(-1) === s.at(-2)) attempts.push(s.slice(0, -1));
    if (!s.endsWith('e')) attempts.push(s + 'e');
  }
  if (w.endsWith('ied') && w.length > 4) attempts.push(w.slice(0, -3) + 'y');
  if (w.endsWith('ed') && !w.endsWith('eed') && w.length > 3) {
    const s = w.slice(0, -2);
    attempts.push(s);
    if (!s.endsWith('e')) attempts.push(s + 'e');
  }
  for (const a of attempts) {
    if (a.length > 2 && ENGLISH_TO_URDU[a] !== undefined) return ENGLISH_TO_URDU[a];
  }
  return null;
}

// ── Urdu grammar: postposition swap & SOV reordering ────────────

const ENG_PREPOSITIONS = new Set([
  'in','on','at','to','from','for','with','by','about','across',
  'through','into','onto','within','without','against','between',
  'among','during','after','before','since','until','throughout',
  'around','above','below','under','over','beside','beyond',
  'toward','towards','behind','beneath','via','despite','including',
  'amid','amidst','along','upon','past',
]);

// Common English verbs (for "to" detection + verb-final move)
const ENG_VERBS = new Set([
  'visit','visits','visited','visiting',
  'drop','drops','dropped','dropping',
  'fall','falls','fell','fallen','falling',
  'rise','rose','risen','rising','rises',
  'surge','surges','surged','surging',
  'kill','kills','killed','killing',
  'arrest','arrests','arrested','arresting',
  'injure','injures','injured','injuring',
  'wound','wounds','wounded','wounding',
  'detain','detains','detained','detaining',
  'kidnap','kidnaps','kidnapped','kidnapping',
  'expect','expects','expected','expecting',
  'forecast','forecasts','forecasted','forecasting',
  'announce','announces','announced','announcing',
  'unveil','unveils','unveiled','unveiling',
  'launch','launches','launched','launching',
  'start','starts','started','starting',
  'continue','continues','continued','continuing',
  'plan','plans','planned','planning',
  'consider','considers','considered','considering',
  'face','faces','faced','facing',
  'win','wins','won','winning',
  'lose','loses','lost','losing',
  'gain','gains','gained','gaining',
  'hold','holds','held','holding',
  'seek','seeks','sought','seeking',
  'call','calls','called','calling',
  'sign','signs','signed','signing',
  'say','says','said','saying',
  'tell','tells','told','telling',
  'report','reports','reported','reporting',
  'confirm','confirms','confirmed','confirming',
  'deny','denies','denied','denying',
  'claim','claims','claimed','claiming',
  'accuse','accuses','accused','accusing',
  'blame','blames','blamed','blaming',
  'charge','charges','charged','charging',
  'sentence','sentences','sentenced','sentencing',
  'convict','convicts','convicted','convicting',
  'commit','commits','committed','committing',
  'attack','attacks','attacked','attacking',
  'strike','strikes','struck','striking',
  'target','targets','targeted','targeting',
  'meet','meets','met','meeting',
  'discuss','discusses','discussed','discussing',
  'agree','agrees','agreed','agreeing',
  'reject','rejects','rejected','rejecting',
  'approve','approves','approved','approving',
  'approve','approves','approved','approving',
  'order','orders','ordered','ordering',
  'warn','warns','warned','warning',
  'urge','urges','urged','urging',
  'demand','demands','demanded','demanding',
  'declare','declares','declared','declaring',
  'release','releases','released','releasing',
  'publish','publishes','published','publishing',
  'issue','issues','issued','issuing',
  'join','joins','joined','joining',
  'leave','leaves','left','leaving',
  'return','returns','returned','returning',
  'arrive','arrives','arrived','arriving',
  'depart','departs','departed','departing',
  'create','creates','created','creating',
  'build','builds','built','building',
  'develop','develops','developed','developing',
  'produce','produces','produced','producing',
  'increase','increases','increased','increasing',
  'decrease','decreases','decreased','decreasing',
  'grow','grows','grew','growing',
  'remain','remains','remained','remaining',
  'become','becomes','became','becoming',
  'seem','seems','seemed','seeming',
  'appear','appears','appeared','appearing',
  'happen','happens','happened','happening',
  'occur','occurs','occurred','occurring',
  'take','takes','took','taking',
  'make','makes','made','making',
  'get','gets','got','getting',
  'set','sets','setting',
  'put','puts','putting',
  'bring','brings','brought','bringing',
  'offer','offers','offered','offering',
  'provide','provides','provided','providing',
  'allow','allows','allowed','allowing',
  'help','helps','helped','helping',
  'support','supports','supported','supporting',
  'lead','leads','led','leading',
  'follow','follows','followed','following',
  'include','includes','included','including',
  'involve','involves','involved','involving',
  'suffer','suffers','suffered','suffering',
  'affect','affects','affected','affecting',
  'spark','sparks','sparked','sparking',
  'trigger','triggers','triggered','triggering',
  'survive','survives','survived','surviving',
  'escape','escapes','escaped','escaping',
  'sweep','sweeps','swept','sweeping',
  'discover','discovers','discovered','discovering',
  'bowl','bowls','bowled','bowling',
  'rule','rules','ruled','ruling',
  'sell','sells','sold','selling',
  'buy','buys','bought','buying',
  'trade','trades','traded','trading',
  'invest','invests','invested','investing',
  'score','scores','scored','scoring',
  'gather','gathers','gathered','gathering',
]);

interface WordUnit {
  eng: string;     // original English lowercase
  urdu: string;    // Urdu translation
  prep: boolean;   // is English preposition
  verb: boolean;   // is English verb (non-auxiliary)
  fixed: boolean;  // already reordered by a higher-priority rule
}

function getUrdu(word: string): string {
  const lower = word.toLowerCase();
  const urdu = ENGLISH_TO_URDU[lower];
  if (urdu !== undefined) return urdu;
  const stemmed = stemWord(lower);
  if (stemmed) return stemmed;
  return transliterateWord(word);
}

function swapNounPhraseAndPostposition(units: WordUnit[]): void {
  for (let i = 0; i < units.length; i++) {
    if (!units[i].prep || units[i].eng === 'to' || units[i].fixed) continue;
    if (i + 1 >= units.length) continue;
    let end = i + 1;
    while (end < units.length && !units[end].prep && !units[end].verb) end++;
    if (end > i + 1) {
      const prep = units.splice(i, 1)[0];
      units.splice(end - 1, 0, prep);
      i = end - 1;
    }
  }
}

const PASSIVE_VERBS = new Set(['killed','injured','dead','arrested','wounded','detained','kidnapped','found','expected']);

export function translateToUrdu(englishText: string): string {
  const tokens = englishText.split(/\s+/);
  const units: WordUnit[] = [];

  // Phase 1: translate
  for (const tok of tokens) {
    const eng = tok.replace(/[^a-zA-Z0-9\-']/g, '').toLowerCase();
    units.push({
      eng,
      urdu: getUrdu(tok),
      prep: ENG_PREPOSITIONS.has(eng),
      verb: ENG_VERBS.has(eng),
      fixed: false,
    });
  }

  // Phase 2: remove "to" before verbs (infinitive marker)
  for (let i = 0; i < units.length - 1; i++) {
    if (units[i].eng === 'to' && units[i + 1].verb) {
      units[i].urdu = '';
    }
  }

  // Phase 3: passive reordering — [X] killed [prep] [Y] → [Y] [prep] [X] killed
  for (let i = 0; i < units.length; i++) {
    if (PASSIVE_VERBS.has(units[i].eng)) {
      let prepIdx = -1;
      for (let j = i + 1; j < units.length; j++) {
        if (units[j].prep && units[j].eng !== 'to') { prepIdx = j; break; }
      }
      if (prepIdx !== -1 && prepIdx < units.length - 1) {
        const before = units.slice(0, i);
        const verb = units[i];
        const prep = units[prepIdx];
        const afterPrep = units.slice(prepIdx + 1);
        const middle = units.slice(i + 1, prepIdx);
        // Correct Urdu order: location + prep + subject + verb
        const reordered = [...afterPrep, prep, ...before, ...middle, verb];
        prep.fixed = true;
        units.length = 0;
        units.push(...reordered);
        break;
      }
    }
  }

  // Phase 4: postposition swap (skip prepositions already placed by phase 3)
  swapNounPhraseAndPostposition(units);

  // Phase 5: verb-final — move the main verb to the end
  let verbIdx = -1;
  for (let i = 0; i < units.length - 1; i++) {
    if (units[i].verb && !units[i].prep && units[i].eng !== 'to') {
      if (units.slice(i + 1).some(u => u.urdu)) {
        verbIdx = i;
        break;
      }
    }
  }
  if (verbIdx !== -1) {
    const verb = units.splice(verbIdx, 1)[0];
    // Insert genitive connector between object noun and action verb
    // For action verbs like "visit", insert genitive connector after the object
    if (verb.eng === 'visit' || verb.eng === 'visits' || verb.eng === 'visited') {
      if (verbIdx < units.length) {
        units.splice(verbIdx + 1, 0, {
          eng: '', urdu: 'کا', prep: false, verb: false, fixed: true,
        });
      }
    }
    units.push(verb);
  }

  let parts = units.map(u => u.urdu).filter(Boolean);
  // Remove consecutive duplicate words (e.g., "اضافہ اضافہ")
  parts = parts.filter((w, i) => i === 0 || w !== parts[i - 1]);
  return fixTranslations(parts.join(' '));
}

// ── Post-translation fixes for known Google Translate errors ──
const TRANSLATION_FIXES: [RegExp, string][] = [
  [/\bAI\b/g, 'مصنوعی ذہانت (AI)'],
  [/\bUK\b/g, 'برطانیہ'],
];

// Strip common raw English suffixes/phrases left untranslated in headlines
const RAW_ENGLISH_PATTERNS: RegExp[] = [
  /\[!\[.*?\]\(.*?\)\]/,                          // markdown image: [![alt](url)]
  /!\[.*?\]\(.*?\)/g,                              // raw markdown image: ![alt](url)
  /\[.*?\]\(.*?\)/g,                               // generic markdown link: [text](url)
  /[-–—]\s*(business\s+live|live|business|latest|update|breaking)\s*$/gi,
  /[-–—]\s*[a-zA-Z\s]{2,40}$/g,
  /\b(live|breaking|update)\s*[-–—]\s*/gi,
];

function fixTranslations(text: string): string {
  let result = text;
  for (const [pattern, replacement] of TRANSLATION_FIXES) {
    result = result.replace(pattern, replacement);
  }
  for (const pattern of RAW_ENGLISH_PATTERNS) {
    result = result.replace(pattern, '').trim();
  }
  return result;
}

export function cleanArticleTitle(title: string): string {
  if (!title) return title;
  let result = title;
  for (const pattern of RAW_ENGLISH_PATTERNS) {
    result = result.replace(pattern, '').trim();
  }
  result = result.replace(/\bAI\b/g, 'مصنوعی ذہانت (AI)');
  result = result.replace(/\bUK\b/g, 'برطانیہ');
  /* Display-time sanitization for known Urdu misspellings that may already
     exist in the database from earlier ingestion pipeline runs. */
  result = result.replace(/\bسپَچے\b/g, 'اسپیس ایکس');
  result = result.replace(/\bSpaceX\b/gi, 'اسپیس ایکس');
  result = result.replace(/\bتن\b(?!\s*ٹریلین)/g, 'ٹریلین');
  result = result.replace(/\btrillion\b/gi, 'ٹریلین');
  result = result.replace(/\bbillion\b/gi, 'ارب');
  result = result.replace(/\bmillion\b/gi, 'ملین');
  return result.trim();
}

export async function translateToUrduAsync(englishText: string): Promise<string> {
  if (!englishText.trim()) return '';
  const sent = englishText.slice(0, 500);
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=ur&dt=t&q=${encodeURIComponent(sent)}`;
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 10000);
      const res = await fetch(url, { signal: controller.signal });
      clearTimeout(timer);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = (await res.json()) as [[[string, string]]];
      const translated = data?.[0]?.[0]?.[0];
      if (translated) {
        const cleaned = await transliterateRemainingEnglish(translated);
        return fixTranslations(cleaned);
      }
      throw new Error('No translation');
    } catch (e) {
      if (attempt === 1) {
        console.warn('Google Translate failed, using local:', (e as Error)?.message || e);
        return translateToUrdu(englishText);
      }
      await new Promise(r => setTimeout(r, 1000));
    }
  }
  return translateToUrdu(englishText);
}

const LATIN_RE = /[a-zA-Z]{2,}/g;

async function transliterateRemainingEnglish(text: string): Promise<string> {
  const matches = text.match(LATIN_RE);
  if (!matches) return text;
  const unique = Array.from(new Set(matches));
  try {
    const query = unique.join(' ');
    const url = `https://inputtools.google.com/request?text=${encodeURIComponent(query)}&itc=ur-t-i0-und&num=1`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 5000);
    const res = await fetch(url, { signal: controller.signal });
    clearTimeout(timer);
    if (!res.ok) return text;
    const data = (await res.json()) as [string, [string, string[]][]];
    if (data?.[0] !== 'SUCCESS') return text;
    const resultStr = data[1]?.[0]?.[1]?.[0];
    if (!resultStr) return text;
    const replacements = resultStr.split(' ');
    if (replacements.length !== unique.length) return text;
    const map = new Map<string, string>();
    for (let i = 0; i < unique.length; i++) {
      if (replacements[i] && replacements[i] !== unique[i]) {
        map.set(unique[i], replacements[i]);
      }
    }
    return text.replace(LATIN_RE, (m) => map.get(m) || m);
  } catch {
    return text;
  }
}

const TWO_LETTER_KEEP = new Set(['ai', 'us', 'uk', 'eu', 'tv', 'pc', 'ceo', 'cfo', 'cto', '5g', '4g', 'psl', 'imf', 'cpec', 'odi', 't20']);

export function extractEnglishKeywords(text: string): string[] {
  const translated = translateToEnglish(text);
  const words = translated.split(/\s+/);
  const wordFreq: Record<string, number> = {};

  const stopWords = new Set([
    'the', 'a', 'an', 'in', 'of', 'to', 'and', 'is', 'are', 'was',
    'for', 'on', 'by', 'with', 'at', 'from', 'as', 'be', 'has', 'had',
    'its', 'but', 'not', 'or',
  ]);

  for (const word of words) {
    const cleaned = word.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
    if (!cleaned || stopWords.has(cleaned)) continue;
    if (cleaned.length < 3 && !TWO_LETTER_KEEP.has(cleaned)) continue;
    wordFreq[cleaned] = (wordFreq[cleaned] || 0) + 1;
  }

  return Object.entries(wordFreq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6)
    .map(([word]) => word);
}
