export const URDU_TO_ENGLISH: Record<string, string> = {
  'پاکستان': 'Pakistan',
  'پاکستانی': 'Pakistani',
  'دنیا': 'world',
  'کھیل': 'sports',
  'کاروبار': 'business',
  'شوبز': 'entertainment',
  'سائنس و ٹیکنالوجی': 'technology',
  'صحت': 'health',
  'تعلیم': 'education',
  'سیاست': 'politics',
  'معیشت': 'economy',
  'کرکٹ': 'cricket',
  'فٹ بال': 'football',
  'فلم': 'movie',
  'موبائل': 'mobile',
  'ایپس': 'apps',
  'وائرس': 'virus',
  'عدالت': 'court',
  'انتخابات': 'election',
  'حکومت': 'government',
  'وزیراعظم': 'prime minister',
  'صدر': 'president',
  'آئی ایم ایف': 'IMF',
  'اسٹاک مارکیٹ': 'stock market',
  'سمارٹ فون': 'smartphone',
  'کیمرہ': 'camera',
  'بینک': 'bank',
  'تعلیمی': 'educational',
  'امتحانات': 'exams',
  'ہسپتال': 'hospital',
  'اداکار': 'actor',
  'گرمی': 'summer heat',
  'موسم': 'weather',
  'درجہ حرارت': 'temperature',
  'برآمدات': 'exports',
  'توانائی': 'energy',
  'تیل': 'oil',
  'قدرتی آفت': 'natural disaster',
  'زلزلہ': 'earthquake',
  'سیلاب': 'flood',
  'بارش': 'rain',
  'اجلاس': 'summit meeting',
  'معاہدہ': 'agreement',
  'امن': 'peace',
  'جنگ بندی': 'ceasefire',
  'جنگ': 'war',
  'فوج': 'army',
  'پولیس': 'police',
  'عدالت عظمی': 'supreme court',
  'جج': 'judge',
  'ووٹ': 'vote',
  'قانون': 'law',
  'منصوبہ': 'project plan',
  'منصوبے': 'project',
  'ترقی': 'development',
  'غربت': 'poverty',
  'تعمیر': 'construction',
  'ریلوے': 'railway',
  'سڑک': 'road highway',
  'پانی': 'water',
  'بجلی': 'electricity',
  'زراعت': 'agriculture farming',
  'فصل': 'crop harvest',
  'اضافہ': 'increase',
  'کمی': 'decrease',
  'شرح': 'rate',
  'متوقع': 'expected',
  'مہنگائی': 'inflation',
  'بجٹ': 'budget',
  'وفاقی': 'federal',
  'تنخواہوں': 'salaries',
  'آمد': 'arrival',
  'گرما': 'summer',
  'سالانہ': 'annual',
  'اداروں': 'institutions',
  'آغاز': 'start',
  'سہولتوں': 'facilities',
  'بہتری': 'improvement',
  'مشہور': 'famous',
  'اعلان': 'announcement',
  'چین': 'China',
  'اقتصادی': 'economic',
  'راہداری': 'corridor',
  'تیزی': 'rapid growth',
  'شیڈول': 'schedule',
  'جاری': 'released ongoing',
  'روپے': 'rupee',
  'قدر': 'value',
  'ڈالر': 'dollar',
  'سستا': 'cheaper',
  'نمایاں': 'significant',
  'ڈرامہ': 'drama',
  'سیریل': 'serial',
  'بھارت': 'India',
  'مقبولیت': 'popularity',
  'حاصل': 'gained',
  'لوک': 'folk',
  'میوزک': 'music',
  'فیسٹیول': 'festival',
  'انعقاد': 'held',
  'فنکاروں': 'artists',
  'شرکت': 'participation',
  'سروس': 'service',
  'اجراء': 'launch',
  'تیاریاں': 'preparations',
  'ڈینگی': 'dengue',
  'بخار': 'fever',
  'بچاؤ': 'prevention',
  'احتیاطی': 'preventive',
  'تدابیر': 'measures',
  'پولیو': 'polio',
  'قطرہ': 'drop',
  'مہم': 'campaign',
  'نصاب': 'curriculum',
  'عملی': 'practical',
  'زندگی': 'life',
  'توجہ': 'focus',
  'طلبہ': 'students',
  'اسکالرشپ': 'scholarship',
  'پروگرام': 'program',
  'پی ایس ایل': 'PSL',
  'انڈیکس': 'index',
  'لیگ': 'league',
  'ٹیم': 'team',
  'کھلاڑیوں': 'players',
  'میچ': 'match',
  'ٹورنامنٹ': 'tournament',
  'سیریز': 'series',
  'شکست': 'defeat',
  'فتح': 'victory',
  'ریکارڈ': 'record',
  'لہر': 'wave',
  'سی پیک': 'CPEC',
  'قومی': 'national',
  'بورڈ': 'board',
  'سروسز': 'services',
  'نیٹ': 'internet',
  'امتحان': 'exam examination',
  'نتیجہ': 'result outcome',
  'پوزیشن': 'position rank',
  'درجہ': 'positiongrade ranking',
  'سرٹیفکیٹ': 'certificate',
  'ڈگری': 'degree',
  'ماسٹر': 'master',
  'ڈاکٹر': 'doctor',
  'انجینئرنگ': 'engineering',
  'میڈیکل': 'medical',
  'فن': 'art fine arts',
  'کاروباری': 'business entrepreneurial',
  'وظیفہ': 'job employment',
  'بیروزگاری': 'unemployment',
  'معاشی': 'economic',
  'مالی': 'financial monetary',
  'خزانہ': 'treasury finance',
  'ٹیکس': 'tax',
  'محصول': 'revenue',
  'خرچ': 'expenditure expense',
  'قرض': 'debt loan',
  'بچت': 'savings',
  'منافع': 'profit',
  'نقصان': 'loss',
  'سرمایہ': 'capital investment',
  'کارخانہ': 'factory industry',
  'پیداوار': 'production output',
  'مانگ': 'demand',
  'رسد': 'supply',
  'اجناس': 'commodities goods',
  'درآمد': 'import',
  'برآمد': 'export',
  'ادھار': 'loan borrowing',
  'شرح سود': 'interest rate',
  'مبادلہ': 'exchange',
  'زر': 'gold money',
  'سون': 'gold',
  'چاندی': 'silver',
  'پیٹرول': 'petrol gasoline',
  'ڈیزل': 'diesel',

  'یورپ': 'Europe',
  'امریکی': 'American US',
  'صدارتی': 'presidential',
  'فلسطین': 'Palestine',
  'اقوام متحدہ': 'United Nations',
  'کوششیں': 'efforts',
  'مصنوعی ذہانت': 'artificial intelligence',
  'شعبے': 'sector',
  'انقلاب': 'revolution',
  'نیا': 'new',
  'نئی': 'new',
  'نئے': 'new',
  'مارکیٹ': 'market',
  'جلد': 'soon',
  'متعارف': 'introduced',
  'تبدیلی': 'change',
  'ملک': 'country',
  'شہر': 'city',
  'وزیر': 'minister',
  'صوبائی': 'provincial',
  'مقامی': 'local',
  'عالمی': 'global',
  'فیصلہ': 'decision',
  'اہم': 'important',
  'بڑے': 'major',
  'کامیاب': 'successful',
  'شامل': 'included',
  'تازہ': 'fresh latest',
  'ترجمان': 'spokesperson',
  'ذرائع': 'sources',
  'غیر ملکی': 'foreign',
  'مقابلہ': 'competition',
  'فعال': 'active',
  'قائم': 'established',
  'واقع': 'occurred',
  'اور': 'and',
  'کے': 'of',
  'میں': 'in',
  'لیے': 'for',
  'سے': 'from',
  'کا': 'of',
  'کی': 'of',
  'کو': 'to',
  'پر': 'on',
  'طے پا گیا': 'finalized',
  'پیش': 'presented',
  'توڑ': 'broke',
  'تیز': 'intensified',
  'انقلابی': 'revolutionary',
  'تیار': 'prepared',
  'کا آغاز': 'started',
  'ہے': 'is',
  'ہیں': 'are',
  'گیا': 'was',
  'گئی': 'was',
  'گئے': 'were',
  'ہو': 'been',
  'خلاف': 'against',
  'ساتھ': 'with',
  'بعد': 'after',
  'قبل': 'before',
  'دوران': 'during',
  'بغیر': 'without',
  'صرف': 'only',
  'ہر': 'every',
  'کچھ': 'some',
  'بہت': 'very',
  'ان': 'these',
  'اس': 'this',
  'ایک': 'one',
  'اور بھی': 'more',
  'دیگر': 'other',
  'مزید': 'further',
  'نے': '',
  'بھی': 'also',
  'ہوا': 'was',
  'ہوئی': 'was',
  'ہوئے': 'were',
  'رہا': 'remained',
  'رہی': 'remained',
  'رہے': 'remained',
  'کیا': 'done',
  'کئے': 'done',
  'دی': 'given',
  'دیا': 'given',
  'دیے': 'given',
  'جا': 'being',
  'گا': 'will',
  'گی': 'will',
  'ہوگا': 'will be',
  'ہوگی': 'will be',
  'ہوں گے': 'will be',
  'سکتا': 'can',
  'سکتی': 'can',
  'سکتے': 'can',
  'چاہیے': 'should',
  'ضروری': 'necessary',
  'ممکن': 'possible',
  'کہ': 'that',
  'جن': 'who',
  'جو': 'which',
  'وہ': 'that',
  'یہ': 'this',
  'آپ': 'you',
  'ہم': 'we',
  'انہوں': 'they',
  'ان کا': 'their',
  'اپنے': 'own',
  'اپنی': 'own',
  'اپنا': 'own',
};

export function translateToEnglish(urduText: string): string {
  let result = urduText;
  const sorted = Object.entries(URDU_TO_ENGLISH).sort((a, b) => b[0].length - a[0].length);
  for (const [urdu, english] of sorted) {
    result = result.replace(new RegExp(urdu, 'g'), english);
  }
  return result;
}

const URDU_REGEX = /[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]/g;

export function translateToCleanEnglish(urduText: string): string {
  const translated = translateToEnglish(urduText);
  return translated.replace(URDU_REGEX, '').replace(/\s+/g, ' ').trim();
}

const TWO_LETTER_KEEP = new Set(['ai', 'us', 'uk', 'eu', 'tv', 'pc', 'ceo', 'cfo', 'cto', '5g', '4g', 'psl', 'imf', 'cpec', 'odi', 't20']);

export function extractEnglishKeywords(text: string): string[] {
  const translated = translateToEnglish(text);
  const words = translated.split(/\s+/);
  const wordFreq: Record<string, number> = {};

  const stopWords = new Set([
    'the', 'a', 'an', 'in', 'of', 'to', 'and', 'is', 'are', 'was',
    'for', 'on', 'by', 'with', 'at', 'from', 'as', 'be', 'has', 'had',
    'its', 'but', 'not', 'or',
  ]);

  for (const word of words) {
    const cleaned = word.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
    if (!cleaned || stopWords.has(cleaned)) continue;
    if (cleaned.length < 3 && !TWO_LETTER_KEEP.has(cleaned)) continue;
    wordFreq[cleaned] = (wordFreq[cleaned] || 0) + 1;
  }

  return Object.entries(wordFreq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6)
    .map(([word]) => word);
}
